# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\easyLearn_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(941, 728)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 20, 861, 621))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_workingdir = QtWidgets.QGroupBox(self.widget)
        self.groupBox_workingdir.setTitle("")
        self.groupBox_workingdir.setObjectName("groupBox_workingdir")
        self.WholeGroupBox = QtWidgets.QGroupBox(self.groupBox_workingdir)
        self.WholeGroupBox.setGeometry(QtCore.QRect(5, 90, 841, 401))
        self.WholeGroupBox.setObjectName("WholeGroupBox")
        self.groupBox_files = QtWidgets.QGroupBox(self.WholeGroupBox)
        self.groupBox_files.setGeometry(QtCore.QRect(580, 30, 241, 351))
        self.groupBox_files.setObjectName("groupBox_files")
        self.listView_files = QtWidgets.QListView(self.groupBox_files)
        self.listView_files.setGeometry(QtCore.QRect(20, 30, 201, 261))
        self.listView_files.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listView_files.setObjectName("listView_files")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_files)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 300, 201, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_addfiles = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_addfiles.setToolTipDuration(-5)
        self.pushButton_addfiles.setObjectName("pushButton_addfiles")
        self.horizontalLayout_3.addWidget(self.pushButton_addfiles)
        self.pushButton_removefiles = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_removefiles.setObjectName("pushButton_removefiles")
        self.horizontalLayout_3.addWidget(self.pushButton_removefiles)
        self.pushButton_clearfiles = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_clearfiles.setObjectName("pushButton_clearfiles")
        self.horizontalLayout_3.addWidget(self.pushButton_clearfiles)
        self.groupBox_modality = QtWidgets.QGroupBox(self.WholeGroupBox)
        self.groupBox_modality.setGeometry(QtCore.QRect(290, 30, 241, 351))
        self.groupBox_modality.setObjectName("groupBox_modality")
        self.listView_modalities = QtWidgets.QListView(self.groupBox_modality)
        self.listView_modalities.setGeometry(QtCore.QRect(20, 30, 201, 261))
        self.listView_modalities.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listView_modalities.setObjectName("listView_modalities")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_modality)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 300, 201, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_addmodalities = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_addmodalities.setToolTipDuration(-5)
        self.pushButton_addmodalities.setObjectName("pushButton_addmodalities")
        self.horizontalLayout_2.addWidget(self.pushButton_addmodalities)
        self.pushButton_removemodalites = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_removemodalites.setObjectName("pushButton_removemodalites")
        self.horizontalLayout_2.addWidget(self.pushButton_removemodalites)
        self.pushButton_clearmodalities = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearmodalities.setObjectName("pushButton_clearmodalities")
        self.horizontalLayout_2.addWidget(self.pushButton_clearmodalities)
        self.groupBox_group = QtWidgets.QGroupBox(self.WholeGroupBox)
        self.groupBox_group.setGeometry(QtCore.QRect(10, 30, 241, 351))
        self.groupBox_group.setObjectName("groupBox_group")
        self.listView_groups = QtWidgets.QListView(self.groupBox_group)
        self.listView_groups.setGeometry(QtCore.QRect(20, 30, 201, 261))
        self.listView_groups.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listView_groups.setObjectName("listView_groups")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_group)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 300, 201, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_addgroups = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_addgroups.setToolTipDuration(-5)
        self.pushButton_addgroups.setObjectName("pushButton_addgroups")
        self.horizontalLayout.addWidget(self.pushButton_addgroups)
        self.pushButton_removegroups = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_removegroups.setObjectName("pushButton_removegroups")
        self.horizontalLayout.addWidget(self.pushButton_removegroups)
        self.pushButton_cleargroups = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_cleargroups.setObjectName("pushButton_cleargroups")
        self.horizontalLayout.addWidget(self.pushButton_cleargroups)
        self.label = QtWidgets.QLabel(self.groupBox_workingdir)
        self.label.setGeometry(QtCore.QRect(5, 15, 136, 16))
        self.label.setObjectName("label")
        self.widget1 = QtWidgets.QWidget(self.groupBox_workingdir)
        self.widget1.setGeometry(QtCore.QRect(5, 39, 791, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_workingdir = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_workingdir.setObjectName("lineEdit_workingdir")
        self.horizontalLayout_4.addWidget(self.lineEdit_workingdir)
        self.browser_workingdir = QtWidgets.QPushButton(self.widget1)
        self.browser_workingdir.setObjectName("browser_workingdir")
        self.horizontalLayout_4.addWidget(self.browser_workingdir)
        self.verticalLayout.addWidget(self.groupBox_workingdir)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 941, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar) 

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_workingdir, self.listView_groups)
        MainWindow.setTabOrder(self.listView_groups, self.pushButton_addgroups)
        MainWindow.setTabOrder(self.pushButton_addgroups, self.pushButton_cleargroups)
        MainWindow.setTabOrder(self.pushButton_cleargroups, self.listView_modalities)
        MainWindow.setTabOrder(self.listView_modalities, self.pushButton_addmodalities)
        MainWindow.setTabOrder(self.pushButton_addmodalities, self.pushButton_removemodalites)
        MainWindow.setTabOrder(self.pushButton_removemodalites, self.pushButton_clearmodalities)
        MainWindow.setTabOrder(self.pushButton_clearmodalities, self.pushButton_addfiles)
        MainWindow.setTabOrder(self.pushButton_addfiles, self.pushButton_removefiles)
        MainWindow.setTabOrder(self.pushButton_removefiles, self.pushButton_clearfiles)
        MainWindow.setTabOrder(self.pushButton_clearfiles, self.listView_files)
        MainWindow.setTabOrder(self.listView_files, self.pushButton_removegroups)
        MainWindow.setTabOrder(self.pushButton_removegroups, self.browser_workingdir)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "easyLearn"))
        self.WholeGroupBox.setTitle(_translate("MainWindow", "Inputs"))
        self.groupBox_files.setTitle(_translate("MainWindow", "Files"))
        self.pushButton_addfiles.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>push the button then close program</p></body></html>"))
        self.pushButton_addfiles.setText(_translate("MainWindow", "Add"))
        self.pushButton_removefiles.setText(_translate("MainWindow", "Remove"))
        self.pushButton_clearfiles.setText(_translate("MainWindow", "Clear"))
        self.groupBox_modality.setTitle(_translate("MainWindow", "Modalities"))
        self.pushButton_addmodalities.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>push the button then close program</p></body></html>"))
        self.pushButton_addmodalities.setText(_translate("MainWindow", "Add"))
        self.pushButton_removemodalites.setText(_translate("MainWindow", "Remove"))
        self.pushButton_clearmodalities.setText(_translate("MainWindow", "Clear"))
        self.groupBox_group.setTitle(_translate("MainWindow", "Groups"))
        self.pushButton_addgroups.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>push the button then close program</p></body></html>"))
        self.pushButton_addgroups.setText(_translate("MainWindow", "Add"))
        self.pushButton_removegroups.setText(_translate("MainWindow", "Remove"))
        self.pushButton_cleargroups.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow", "Working Directory"))
        self.browser_workingdir.setText(_translate("MainWindow", "Browser"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

