# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\My_Codes\easylearn-fmri\eslearn\gui_test\easylearn_gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 612)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(350, 450))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_all_ptb = QtWidgets.QGridLayout()
        self.gridLayout_all_ptb.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_all_ptb.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_all_ptb.setSpacing(10)
        self.gridLayout_all_ptb.setObjectName("gridLayout_all_ptb")
        self.data_input = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_input.sizePolicy().hasHeightForWidth())
        self.data_input.setSizePolicy(sizePolicy)
        self.data_input.setStyleSheet("")
        self.data_input.setIconSize(QtCore.QSize(30, 30))
        self.data_input.setObjectName("data_input")
        self.gridLayout_all_ptb.addWidget(self.data_input, 3, 0, 1, 2)
        self.feature_selection = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feature_selection.sizePolicy().hasHeightForWidth())
        self.feature_selection.setSizePolicy(sizePolicy)
        self.feature_selection.setIconSize(QtCore.QSize(30, 30))
        self.feature_selection.setObjectName("feature_selection")
        self.gridLayout_all_ptb.addWidget(self.feature_selection, 5, 0, 1, 2)
        self.statistical_analysis = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statistical_analysis.sizePolicy().hasHeightForWidth())
        self.statistical_analysis.setSizePolicy(sizePolicy)
        self.statistical_analysis.setIconSize(QtCore.QSize(30, 30))
        self.statistical_analysis.setObjectName("statistical_analysis")
        self.gridLayout_all_ptb.addWidget(self.statistical_analysis, 9, 0, 1, 2)
        self.model_choosing = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_choosing.sizePolicy().hasHeightForWidth())
        self.model_choosing.setSizePolicy(sizePolicy)
        self.model_choosing.setIconSize(QtCore.QSize(30, 30))
        self.model_choosing.setObjectName("model_choosing")
        self.gridLayout_all_ptb.addWidget(self.model_choosing, 6, 0, 1, 2)
        self.feature_reduction = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feature_reduction.sizePolicy().hasHeightForWidth())
        self.feature_reduction.setSizePolicy(sizePolicy)
        self.feature_reduction.setIconSize(QtCore.QSize(30, 30))
        self.feature_reduction.setObjectName("feature_reduction")
        self.gridLayout_all_ptb.addWidget(self.feature_reduction, 4, 0, 1, 2)
        self.model_training = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_training.sizePolicy().hasHeightForWidth())
        self.model_training.setSizePolicy(sizePolicy)
        self.model_training.setIconSize(QtCore.QSize(30, 30))
        self.model_training.setObjectName("model_training")
        self.gridLayout_all_ptb.addWidget(self.model_training, 8, 0, 1, 2)
        self.save_load = QtWidgets.QHBoxLayout()
        self.save_load.setObjectName("save_load")
        self.save_workflow = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_workflow.sizePolicy().hasHeightForWidth())
        self.save_workflow.setSizePolicy(sizePolicy)
        self.save_workflow.setIconSize(QtCore.QSize(30, 30))
        self.save_workflow.setObjectName("save_workflow")
        self.save_load.addWidget(self.save_workflow)
        self.load_workflow = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_workflow.sizePolicy().hasHeightForWidth())
        self.load_workflow.setSizePolicy(sizePolicy)
        self.load_workflow.setIconSize(QtCore.QSize(30, 30))
        self.load_workflow.setObjectName("load_workflow")
        self.save_load.addWidget(self.load_workflow)
        self.gridLayout_all_ptb.addLayout(self.save_load, 10, 0, 1, 2)
        self.gridLayout_all_ptb.setColumnStretch(0, 100)
        self.gridLayout.addLayout(self.gridLayout_all_ptb, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 26))
        self.menubar.setObjectName("menubar")
        self.menueasylearn = QtWidgets.QMenu(self.menubar)
        self.menueasylearn.setObjectName("menueasylearn")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menueasylearn.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.data_input.setText(_translate("MainWindow", "Data input"))
        self.feature_selection.setText(_translate("MainWindow", "Feature selection"))
        self.statistical_analysis.setText(_translate("MainWindow", "Statistical analysis"))
        self.model_choosing.setText(_translate("MainWindow", "Model choosing"))
        self.feature_reduction.setText(_translate("MainWindow", "Feature reduction"))
        self.model_training.setText(_translate("MainWindow", "Model training"))
        self.save_workflow.setText(_translate("MainWindow", " Save workflow"))
        self.load_workflow.setText(_translate("MainWindow", "Load workflow"))
        self.menueasylearn.setTitle(_translate("MainWindow", "File(&F)"))

