# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './easylearn_machine_learning_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 809)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_machine_learning_type = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_machine_learning_type.setObjectName("groupBox_machine_learning_type")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_machine_learning_type)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_classification = QtWidgets.QRadioButton(self.groupBox_machine_learning_type)
        self.radioButton_classification.setObjectName("radioButton_classification")
        self.horizontalLayout.addWidget(self.radioButton_classification)
        self.radioButton_regression = QtWidgets.QRadioButton(self.groupBox_machine_learning_type)
        self.radioButton_regression.setObjectName("radioButton_regression")
        self.horizontalLayout.addWidget(self.radioButton_regression)
        self.radioButton_clustering = QtWidgets.QRadioButton(self.groupBox_machine_learning_type)
        self.radioButton_clustering.setObjectName("radioButton_clustering")
        self.horizontalLayout.addWidget(self.radioButton_clustering)
        self.radioButton_deeplearning = QtWidgets.QRadioButton(self.groupBox_machine_learning_type)
        self.radioButton_deeplearning.setObjectName("radioButton_deeplearning")
        self.horizontalLayout.addWidget(self.radioButton_deeplearning)
        self.gridLayout_19.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_machine_learning_type, 0, 0, 1, 1)
        self.stackedWidget_machine_learning_type = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_machine_learning_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget_machine_learning_type.setObjectName("stackedWidget_machine_learning_type")
        self.stackedWidgetPage_classification = QtWidgets.QWidget()
        self.stackedWidgetPage_classification.setObjectName("stackedWidgetPage_classification")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.stackedWidgetPage_classification)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_method = QtWidgets.QGroupBox(self.stackedWidgetPage_classification)
        self.groupBox_method.setObjectName("groupBox_method")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_method)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_classification_gaussianprocess = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_gaussianprocess.setObjectName("radioButton_classification_gaussianprocess")
        self.gridLayout_5.addWidget(self.radioButton_classification_gaussianprocess, 4, 0, 1, 1)
        self.radioButton_classification_randomforest = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_randomforest.setObjectName("radioButton_classification_randomforest")
        self.gridLayout_5.addWidget(self.radioButton_classification_randomforest, 6, 0, 1, 1)
        self.radioButton_classification_svm = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_svm.setChecked(False)
        self.radioButton_classification_svm.setObjectName("radioButton_classification_svm")
        self.gridLayout_5.addWidget(self.radioButton_classification_svm, 2, 0, 1, 1)
        self.radioButton_classification_lr = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_lr.setCheckable(True)
        self.radioButton_classification_lr.setChecked(False)
        self.radioButton_classification_lr.setObjectName("radioButton_classification_lr")
        self.gridLayout_5.addWidget(self.radioButton_classification_lr, 0, 0, 1, 1)
        self.radioButton_classification_adaboost = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_adaboost.setObjectName("radioButton_classification_adaboost")
        self.gridLayout_5.addWidget(self.radioButton_classification_adaboost, 9, 0, 1, 1)
        self.radioButton_classification_ridge = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_ridge.setObjectName("radioButton_classification_ridge")
        self.gridLayout_5.addWidget(self.radioButton_classification_ridge, 3, 0, 1, 1)
        self.radioButton_classification_linearsvc = QtWidgets.QRadioButton(self.groupBox_method)
        self.radioButton_classification_linearsvc.setChecked(False)
        self.radioButton_classification_linearsvc.setObjectName("radioButton_classification_linearsvc")
        self.gridLayout_5.addWidget(self.radioButton_classification_linearsvc, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_method, 0, 0, 1, 1)
        self.groupBox_setting = QtWidgets.QGroupBox(self.stackedWidgetPage_classification)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_setting.sizePolicy().hasHeightForWidth())
        self.groupBox_setting.setSizePolicy(sizePolicy)
        self.groupBox_setting.setMinimumSize(QtCore.QSize(100, 0))
        self.groupBox_setting.setObjectName("groupBox_setting")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_setting)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget_classification_setting = QtWidgets.QStackedWidget(self.groupBox_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_classification_setting.sizePolicy().hasHeightForWidth())
        self.stackedWidget_classification_setting.setSizePolicy(sizePolicy)
        self.stackedWidget_classification_setting.setMinimumSize(QtCore.QSize(200, 0))
        self.stackedWidget_classification_setting.setObjectName("stackedWidget_classification_setting")
        self.to_lr = QtWidgets.QWidget()
        self.to_lr.setObjectName("to_lr")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.to_lr)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lineEdit_clf_lr_l1ratio = QtWidgets.QLineEdit(self.to_lr)
        self.lineEdit_clf_lr_l1ratio.setObjectName("lineEdit_clf_lr_l1ratio")
        self.gridLayout_11.addWidget(self.lineEdit_clf_lr_l1ratio, 1, 1, 1, 1)
        self.comboBox_clf_lr_penalty = QtWidgets.QComboBox(self.to_lr)
        self.comboBox_clf_lr_penalty.setObjectName("comboBox_clf_lr_penalty")
        self.comboBox_clf_lr_penalty.addItem("")
        self.comboBox_clf_lr_penalty.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_clf_lr_penalty, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.to_lr)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.to_lr)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.to_lr)
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_clf_lr_C = QtWidgets.QLineEdit(self.to_lr)
        self.lineEdit_clf_lr_C.setObjectName("lineEdit_clf_lr_C")
        self.gridLayout_11.addWidget(self.lineEdit_clf_lr_C, 2, 1, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_lr)
        self.to_linearSVC = QtWidgets.QWidget()
        self.to_linearSVC.setObjectName("to_linearSVC")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.to_linearSVC)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.comboBox_clf_linearsvc_multiclass = QtWidgets.QComboBox(self.to_linearSVC)
        self.comboBox_clf_linearsvc_multiclass.setObjectName("comboBox_clf_linearsvc_multiclass")
        self.comboBox_clf_linearsvc_multiclass.addItem("")
        self.comboBox_clf_linearsvc_multiclass.addItem("")
        self.gridLayout_30.addWidget(self.comboBox_clf_linearsvc_multiclass, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.to_linearSVC)
        self.label_36.setObjectName("label_36")
        self.gridLayout_30.addWidget(self.label_36, 1, 0, 1, 1)
        self.label_C_2 = QtWidgets.QLabel(self.to_linearSVC)
        self.label_C_2.setObjectName("label_C_2")
        self.gridLayout_30.addWidget(self.label_C_2, 0, 0, 1, 1)
        self.lineEdit_clf_linearsvc_c = QtWidgets.QLineEdit(self.to_linearSVC)
        self.lineEdit_clf_linearsvc_c.setObjectName("lineEdit_clf_linearsvc_c")
        self.gridLayout_30.addWidget(self.lineEdit_clf_linearsvc_c, 0, 1, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_linearSVC)
        self.to_svc = QtWidgets.QWidget()
        self.to_svc.setObjectName("to_svc")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.to_svc)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_gamma = QtWidgets.QLabel(self.to_svc)
        self.label_gamma.setObjectName("label_gamma")
        self.gridLayout_10.addWidget(self.label_gamma, 3, 0, 1, 1)
        self.label_C = QtWidgets.QLabel(self.to_svc)
        self.label_C.setObjectName("label_C")
        self.gridLayout_10.addWidget(self.label_C, 1, 0, 1, 3)
        self.label_clf_svm_kernel = QtWidgets.QLabel(self.to_svc)
        self.label_clf_svm_kernel.setObjectName("label_clf_svm_kernel")
        self.gridLayout_10.addWidget(self.label_clf_svm_kernel, 0, 0, 1, 1)
        self.lineEdit_clf_svm_gamma = QtWidgets.QLineEdit(self.to_svc)
        self.lineEdit_clf_svm_gamma.setObjectName("lineEdit_clf_svm_gamma")
        self.gridLayout_10.addWidget(self.lineEdit_clf_svm_gamma, 3, 4, 1, 1)
        self.comboBox_clf_svm_kernel = QtWidgets.QComboBox(self.to_svc)
        self.comboBox_clf_svm_kernel.setObjectName("comboBox_clf_svm_kernel")
        self.comboBox_clf_svm_kernel.addItem("")
        self.comboBox_clf_svm_kernel.addItem("")
        self.comboBox_clf_svm_kernel.addItem("")
        self.comboBox_clf_svm_kernel.addItem("")
        self.gridLayout_10.addWidget(self.comboBox_clf_svm_kernel, 0, 4, 1, 1)
        self.lineEdit_clf_svm_c = QtWidgets.QLineEdit(self.to_svc)
        self.lineEdit_clf_svm_c.setObjectName("lineEdit_clf_svm_c")
        self.gridLayout_10.addWidget(self.lineEdit_clf_svm_c, 1, 4, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_svc)
        self.to_ridgeclf = QtWidgets.QWidget()
        self.to_ridgeclf.setObjectName("to_ridgeclf")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.to_ridgeclf)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_20 = QtWidgets.QLabel(self.to_ridgeclf)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 0, 1, 1, 1)
        self.lineEdit_clf_ridgeclf_alpha = QtWidgets.QLineEdit(self.to_ridgeclf)
        self.lineEdit_clf_ridgeclf_alpha.setObjectName("lineEdit_clf_ridgeclf_alpha")
        self.gridLayout_14.addWidget(self.lineEdit_clf_ridgeclf_alpha, 0, 2, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_ridgeclf)
        self.to_guassianprocess = QtWidgets.QWidget()
        self.to_guassianprocess.setObjectName("to_guassianprocess")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.to_guassianprocess)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.lineEdit_clf_gaussianprocess_kernel = QtWidgets.QLineEdit(self.to_guassianprocess)
        self.lineEdit_clf_gaussianprocess_kernel.setObjectName("lineEdit_clf_gaussianprocess_kernel")
        self.gridLayout_24.addWidget(self.lineEdit_clf_gaussianprocess_kernel, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.to_guassianprocess)
        self.label_9.setObjectName("label_9")
        self.gridLayout_24.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.to_guassianprocess)
        self.label_10.setObjectName("label_10")
        self.gridLayout_24.addWidget(self.label_10, 0, 0, 1, 1)
        self.comboBox_clf_gaussianprocess_multiclass = QtWidgets.QComboBox(self.to_guassianprocess)
        self.comboBox_clf_gaussianprocess_multiclass.setObjectName("comboBox_clf_gaussianprocess_multiclass")
        self.comboBox_clf_gaussianprocess_multiclass.addItem("")
        self.comboBox_clf_gaussianprocess_multiclass.addItem("")
        self.gridLayout_24.addWidget(self.comboBox_clf_gaussianprocess_multiclass, 1, 1, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_guassianprocess)
        self.to_randomforest = QtWidgets.QWidget()
        self.to_randomforest.setObjectName("to_randomforest")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.to_randomforest)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_24 = QtWidgets.QLabel(self.to_randomforest)
        self.label_24.setObjectName("label_24")
        self.gridLayout_15.addWidget(self.label_24, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.to_randomforest)
        self.label_23.setObjectName("label_23")
        self.gridLayout_15.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.to_randomforest)
        self.label_26.setObjectName("label_26")
        self.gridLayout_15.addWidget(self.label_26, 4, 0, 1, 1)
        self.comboBox_clf_randomforest_criterion = QtWidgets.QComboBox(self.to_randomforest)
        self.comboBox_clf_randomforest_criterion.setObjectName("comboBox_clf_randomforest_criterion")
        self.comboBox_clf_randomforest_criterion.addItem("")
        self.comboBox_clf_randomforest_criterion.addItem("")
        self.gridLayout_15.addWidget(self.comboBox_clf_randomforest_criterion, 1, 1, 1, 1)
        self.lineEdit_clf_randomforest_maxdepth = QtWidgets.QLineEdit(self.to_randomforest)
        self.lineEdit_clf_randomforest_maxdepth.setObjectName("lineEdit_clf_randomforest_maxdepth")
        self.gridLayout_15.addWidget(self.lineEdit_clf_randomforest_maxdepth, 4, 1, 1, 1)
        self.lineEdit_clf_randomforest_estimators = QtWidgets.QLineEdit(self.to_randomforest)
        self.lineEdit_clf_randomforest_estimators.setObjectName("lineEdit_clf_randomforest_estimators")
        self.gridLayout_15.addWidget(self.lineEdit_clf_randomforest_estimators, 2, 1, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_randomforest)
        self.to_adaboost = QtWidgets.QWidget()
        self.to_adaboost.setObjectName("to_adaboost")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.to_adaboost)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.comboBox_clf_adaboost_baseesitmator = QtWidgets.QComboBox(self.to_adaboost)
        self.comboBox_clf_adaboost_baseesitmator.setObjectName("comboBox_clf_adaboost_baseesitmator")
        self.comboBox_clf_adaboost_baseesitmator.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_clf_adaboost_baseesitmator, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.to_adaboost)
        self.label_31.setObjectName("label_31")
        self.gridLayout_16.addWidget(self.label_31, 1, 0, 1, 1)
        self.lineEdit_clf_adaboost_estimators = QtWidgets.QLineEdit(self.to_adaboost)
        self.lineEdit_clf_adaboost_estimators.setObjectName("lineEdit_clf_adaboost_estimators")
        self.gridLayout_16.addWidget(self.lineEdit_clf_adaboost_estimators, 2, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.to_adaboost)
        self.label_29.setObjectName("label_29")
        self.gridLayout_16.addWidget(self.label_29, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.to_adaboost)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 3, 0, 1, 1)
        self.comboBox_clf_adaboost_algoritm = QtWidgets.QComboBox(self.to_adaboost)
        self.comboBox_clf_adaboost_algoritm.setObjectName("comboBox_clf_adaboost_algoritm")
        self.comboBox_clf_adaboost_algoritm.addItem("")
        self.comboBox_clf_adaboost_algoritm.addItem("")
        self.gridLayout_16.addWidget(self.comboBox_clf_adaboost_algoritm, 3, 1, 1, 1)
        self.stackedWidget_classification_setting.addWidget(self.to_adaboost)
        self.to_none = QtWidgets.QWidget()
        self.to_none.setObjectName("to_none")
        self.stackedWidget_classification_setting.addWidget(self.to_none)
        self.gridLayout.addWidget(self.stackedWidget_classification_setting, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_setting, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem, 0, 1, 1, 1)
        self.stackedWidget_machine_learning_type.addWidget(self.stackedWidgetPage_classification)
        self.stackedWidgetPage_regression = QtWidgets.QWidget()
        self.stackedWidgetPage_regression.setObjectName("stackedWidgetPage_regression")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stackedWidgetPage_regression)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.GroupBox_Settting = QtWidgets.QGroupBox(self.stackedWidgetPage_regression)
        self.GroupBox_Settting.setObjectName("GroupBox_Settting")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.GroupBox_Settting)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.stackedWidget_regression = QtWidgets.QStackedWidget(self.GroupBox_Settting)
        self.stackedWidget_regression.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget_regression.setObjectName("stackedWidget_regression")
        self.to_linearregression = QtWidgets.QWidget()
        self.to_linearregression.setObjectName("to_linearregression")
        self.stackedWidget_regression.addWidget(self.to_linearregression)
        self.to_lassoregression = QtWidgets.QWidget()
        self.to_lassoregression.setObjectName("to_lassoregression")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.to_lassoregression)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_11 = QtWidgets.QLabel(self.to_lassoregression)
        self.label_11.setObjectName("label_11")
        self.gridLayout_13.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_regression_lasso_alpha = QtWidgets.QLineEdit(self.to_lassoregression)
        self.lineEdit_regression_lasso_alpha.setObjectName("lineEdit_regression_lasso_alpha")
        self.gridLayout_13.addWidget(self.lineEdit_regression_lasso_alpha, 0, 1, 1, 1)
        self.stackedWidget_regression.addWidget(self.to_lassoregression)
        self.to_ridgeregression = QtWidgets.QWidget()
        self.to_ridgeregression.setObjectName("to_ridgeregression")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.to_ridgeregression)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.stackedWidget_regression.addWidget(self.to_ridgeregression)
        self.to_elasticnet = QtWidgets.QWidget()
        self.to_elasticnet.setObjectName("to_elasticnet")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.to_elasticnet)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_17 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_17.setObjectName("label_17")
        self.gridLayout_20.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_28.setObjectName("label_28")
        self.gridLayout_20.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_regression_elasticnet_l1ratio = QtWidgets.QLineEdit(self.to_elasticnet)
        self.lineEdit_regression_elasticnet_l1ratio.setObjectName("lineEdit_regression_elasticnet_l1ratio")
        self.gridLayout_20.addWidget(self.lineEdit_regression_elasticnet_l1ratio, 0, 1, 1, 1)
        self.lineEdit_regression_elasticnet_alpha = QtWidgets.QLineEdit(self.to_elasticnet)
        self.lineEdit_regression_elasticnet_alpha.setObjectName("lineEdit_regression_elasticnet_alpha")
        self.gridLayout_20.addWidget(self.lineEdit_regression_elasticnet_alpha, 2, 1, 1, 1)
        self.stackedWidget_regression.addWidget(self.to_elasticnet)
        self.to_svm_regression = QtWidgets.QWidget()
        self.to_svm_regression.setObjectName("to_svm_regression")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.to_svm_regression)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.comboBox_regression_svm_kernel = QtWidgets.QComboBox(self.to_svm_regression)
        self.comboBox_regression_svm_kernel.setObjectName("comboBox_regression_svm_kernel")
        self.comboBox_regression_svm_kernel.addItem("")
        self.comboBox_regression_svm_kernel.addItem("")
        self.comboBox_regression_svm_kernel.addItem("")
        self.comboBox_regression_svm_kernel.addItem("")
        self.gridLayout_21.addWidget(self.comboBox_regression_svm_kernel, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.to_svm_regression)
        self.label_3.setObjectName("label_3")
        self.gridLayout_21.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.to_svm_regression)
        self.label.setObjectName("label")
        self.gridLayout_21.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_regression_svm_gamma = QtWidgets.QLineEdit(self.to_svm_regression)
        self.lineEdit_regression_svm_gamma.setObjectName("lineEdit_regression_svm_gamma")
        self.gridLayout_21.addWidget(self.lineEdit_regression_svm_gamma, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.to_svm_regression)
        self.label_4.setObjectName("label_4")
        self.gridLayout_21.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_regression_svm_c = QtWidgets.QLineEdit(self.to_svm_regression)
        self.lineEdit_regression_svm_c.setObjectName("lineEdit_regression_svm_c")
        self.gridLayout_21.addWidget(self.lineEdit_regression_svm_c, 2, 1, 1, 1)
        self.stackedWidget_regression.addWidget(self.to_svm_regression)
        self.to_gaussianprocess = QtWidgets.QWidget()
        self.to_gaussianprocess.setObjectName("to_gaussianprocess")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.to_gaussianprocess)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_5 = QtWidgets.QLabel(self.to_gaussianprocess)
        self.label_5.setObjectName("label_5")
        self.gridLayout_22.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.to_gaussianprocess)
        self.label_6.setObjectName("label_6")
        self.gridLayout_22.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_regression_gaussianprocess_alpha = QtWidgets.QLineEdit(self.to_gaussianprocess)
        self.lineEdit_regression_gaussianprocess_alpha.setObjectName("lineEdit_regression_gaussianprocess_alpha")
        self.gridLayout_22.addWidget(self.lineEdit_regression_gaussianprocess_alpha, 2, 1, 1, 1)
        self.lineEdit_regression_gaussianprocess_kernel = QtWidgets.QLineEdit(self.to_gaussianprocess)
        self.lineEdit_regression_gaussianprocess_kernel.setObjectName("lineEdit_regression_gaussianprocess_kernel")
        self.gridLayout_22.addWidget(self.lineEdit_regression_gaussianprocess_kernel, 0, 1, 1, 1)
        self.stackedWidget_regression.addWidget(self.to_gaussianprocess)
        self.to_randomforest_regression = QtWidgets.QWidget()
        self.to_randomforest_regression.setObjectName("to_randomforest_regression")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.to_randomforest_regression)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_30 = QtWidgets.QLabel(self.to_randomforest_regression)
        self.label_30.setObjectName("label_30")
        self.gridLayout_23.addWidget(self.label_30, 0, 0, 1, 1)
        self.comboBox_regression_randomforest_criterion = QtWidgets.QComboBox(self.to_randomforest_regression)
        self.comboBox_regression_randomforest_criterion.setObjectName("comboBox_regression_randomforest_criterion")
        self.comboBox_regression_randomforest_criterion.addItem("")
        self.comboBox_regression_randomforest_criterion.addItem("")
        self.gridLayout_23.addWidget(self.comboBox_regression_randomforest_criterion, 0, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.to_randomforest_regression)
        self.label_25.setObjectName("label_25")
        self.gridLayout_23.addWidget(self.label_25, 1, 0, 1, 1)
        self.lineEdit_regression_randomforest_estimators = QtWidgets.QLineEdit(self.to_randomforest_regression)
        self.lineEdit_regression_randomforest_estimators.setObjectName("lineEdit_regression_randomforest_estimators")
        self.gridLayout_23.addWidget(self.lineEdit_regression_randomforest_estimators, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.to_randomforest_regression)
        self.label_27.setObjectName("label_27")
        self.gridLayout_23.addWidget(self.label_27, 2, 0, 1, 1)
        self.lineEdit_regression_randomforest_maxdepth = QtWidgets.QLineEdit(self.to_randomforest_regression)
        self.lineEdit_regression_randomforest_maxdepth.setObjectName("lineEdit_regression_randomforest_maxdepth")
        self.gridLayout_23.addWidget(self.lineEdit_regression_randomforest_maxdepth, 2, 1, 1, 1)
        self.stackedWidget_regression.addWidget(self.to_randomforest_regression)
        self.gridLayout_17.addWidget(self.stackedWidget_regression, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.GroupBox_Settting, 0, 2, 1, 1)
        self.Methods = QtWidgets.QGroupBox(self.stackedWidgetPage_regression)
        self.Methods.setObjectName("Methods")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.Methods)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButton_regression_gaussianprocess = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_gaussianprocess.setObjectName("radioButton_regression_gaussianprocess")
        self.gridLayout_6.addWidget(self.radioButton_regression_gaussianprocess, 6, 1, 1, 1)
        self.radioButton_regression_lasso = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_lasso.setObjectName("radioButton_regression_lasso")
        self.gridLayout_6.addWidget(self.radioButton_regression_lasso, 1, 1, 1, 1)
        self.radioButton_regression_randomforest = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_randomforest.setObjectName("radioButton_regression_randomforest")
        self.gridLayout_6.addWidget(self.radioButton_regression_randomforest, 8, 1, 1, 1)
        self.radioButton_regression_ridge = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_ridge.setObjectName("radioButton_regression_ridge")
        self.gridLayout_6.addWidget(self.radioButton_regression_ridge, 2, 1, 1, 1)
        self.radioButton_regression_linearregression = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_linearregression.setObjectName("radioButton_regression_linearregression")
        self.gridLayout_6.addWidget(self.radioButton_regression_linearregression, 0, 1, 1, 1)
        self.radioButton_regression_svm = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_svm.setObjectName("radioButton_regression_svm")
        self.gridLayout_6.addWidget(self.radioButton_regression_svm, 4, 1, 1, 1)
        self.radioButton_regression_elasticnet = QtWidgets.QRadioButton(self.Methods)
        self.radioButton_regression_elasticnet.setObjectName("radioButton_regression_elasticnet")
        self.gridLayout_6.addWidget(self.radioButton_regression_elasticnet, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.Methods, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.Methods.raise_()
        self.GroupBox_Settting.raise_()
        self.stackedWidget_machine_learning_type.addWidget(self.stackedWidgetPage_regression)
        self.stackedWidgetPage_clustering = QtWidgets.QWidget()
        self.stackedWidgetPage_clustering.setObjectName("stackedWidgetPage_clustering")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.stackedWidgetPage_clustering)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.GroupBox_Settting_clustering = QtWidgets.QGroupBox(self.stackedWidgetPage_clustering)
        self.GroupBox_Settting_clustering.setObjectName("GroupBox_Settting_clustering")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.GroupBox_Settting_clustering)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.stackedWidget_clustering = QtWidgets.QStackedWidget(self.GroupBox_Settting_clustering)
        self.stackedWidget_clustering.setObjectName("stackedWidget_clustering")
        self.to_kmeans = QtWidgets.QWidget()
        self.to_kmeans.setObjectName("to_kmeans")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.to_kmeans)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_13 = QtWidgets.QLabel(self.to_kmeans)
        self.label_13.setObjectName("label_13")
        self.gridLayout_26.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.to_kmeans)
        self.label_14.setObjectName("label_14")
        self.gridLayout_26.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.to_kmeans)
        self.label_16.setObjectName("label_16")
        self.gridLayout_26.addWidget(self.label_16, 2, 0, 1, 1)
        self.lineEdit_clustering_kmeans_n_init = QtWidgets.QLineEdit(self.to_kmeans)
        self.lineEdit_clustering_kmeans_n_init.setObjectName("lineEdit_clustering_kmeans_n_init")
        self.gridLayout_26.addWidget(self.lineEdit_clustering_kmeans_n_init, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.to_kmeans)
        self.label_18.setObjectName("label_18")
        self.gridLayout_26.addWidget(self.label_18, 3, 0, 1, 1)
        self.comboBox_clustering_kmeans_init = QtWidgets.QComboBox(self.to_kmeans)
        self.comboBox_clustering_kmeans_init.setObjectName("comboBox_clustering_kmeans_init")
        self.comboBox_clustering_kmeans_init.addItem("")
        self.comboBox_clustering_kmeans_init.addItem("")
        self.gridLayout_26.addWidget(self.comboBox_clustering_kmeans_init, 1, 1, 1, 1)
        self.spinBox_clustering_kmeans_n_clusters = QtWidgets.QSpinBox(self.to_kmeans)
        self.spinBox_clustering_kmeans_n_clusters.setProperty("value", 2)
        self.spinBox_clustering_kmeans_n_clusters.setObjectName("spinBox_clustering_kmeans_n_clusters")
        self.gridLayout_26.addWidget(self.spinBox_clustering_kmeans_n_clusters, 0, 1, 1, 1)
        self.spinBox_clustering_kmeans_random_state = QtWidgets.QSpinBox(self.to_kmeans)
        self.spinBox_clustering_kmeans_random_state.setObjectName("spinBox_clustering_kmeans_random_state")
        self.gridLayout_26.addWidget(self.spinBox_clustering_kmeans_random_state, 3, 1, 1, 1)
        self.stackedWidget_clustering.addWidget(self.to_kmeans)
        self.to_spectralclustering = QtWidgets.QWidget()
        self.to_spectralclustering.setObjectName("to_spectralclustering")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.to_spectralclustering)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_21 = QtWidgets.QLabel(self.to_spectralclustering)
        self.label_21.setObjectName("label_21")
        self.gridLayout_27.addWidget(self.label_21, 0, 0, 1, 1)
        self.comboBox_clustering_spectralclustering_n_clusters = QtWidgets.QSpinBox(self.to_spectralclustering)
        self.comboBox_clustering_spectralclustering_n_clusters.setProperty("value", 2)
        self.comboBox_clustering_spectralclustering_n_clusters.setObjectName("comboBox_clustering_spectralclustering_n_clusters")
        self.gridLayout_27.addWidget(self.comboBox_clustering_spectralclustering_n_clusters, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.to_spectralclustering)
        self.label_22.setObjectName("label_22")
        self.gridLayout_27.addWidget(self.label_22, 1, 0, 1, 1)
        self.lineEdit_clustering_kmeans_n_init_2 = QtWidgets.QLineEdit(self.to_spectralclustering)
        self.lineEdit_clustering_kmeans_n_init_2.setObjectName("lineEdit_clustering_kmeans_n_init_2")
        self.gridLayout_27.addWidget(self.lineEdit_clustering_kmeans_n_init_2, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.to_spectralclustering)
        self.label_19.setObjectName("label_19")
        self.gridLayout_27.addWidget(self.label_19, 2, 0, 1, 1)
        self.spinBox_clustering_spectralclustering_random_state = QtWidgets.QSpinBox(self.to_spectralclustering)
        self.spinBox_clustering_spectralclustering_random_state.setObjectName("spinBox_clustering_spectralclustering_random_state")
        self.gridLayout_27.addWidget(self.spinBox_clustering_spectralclustering_random_state, 2, 1, 1, 1)
        self.stackedWidget_clustering.addWidget(self.to_spectralclustering)
        self.to_agglomerativeclustering = QtWidgets.QWidget()
        self.to_agglomerativeclustering.setObjectName("to_agglomerativeclustering")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.to_agglomerativeclustering)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity = QtWidgets.QComboBox(self.to_agglomerativeclustering)
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.setObjectName("comboBoxit_comboBox_clustering_agglomerativeclustering_affinity")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.addItem("")
        self.gridLayout_28.addWidget(self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity, 2, 1, 1, 2)
        self.label_34 = QtWidgets.QLabel(self.to_agglomerativeclustering)
        self.label_34.setObjectName("label_34")
        self.gridLayout_28.addWidget(self.label_34, 0, 0, 1, 1)
        self.comboBox_clustering_agglomerativeclustering_n_clusters = QtWidgets.QSpinBox(self.to_agglomerativeclustering)
        self.comboBox_clustering_agglomerativeclustering_n_clusters.setProperty("value", 2)
        self.comboBox_clustering_agglomerativeclustering_n_clusters.setObjectName("comboBox_clustering_agglomerativeclustering_n_clusters")
        self.gridLayout_28.addWidget(self.comboBox_clustering_agglomerativeclustering_n_clusters, 0, 1, 1, 2)
        self.label_32 = QtWidgets.QLabel(self.to_agglomerativeclustering)
        self.label_32.setObjectName("label_32")
        self.gridLayout_28.addWidget(self.label_32, 2, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.to_agglomerativeclustering)
        self.label_33.setObjectName("label_33")
        self.gridLayout_28.addWidget(self.label_33, 4, 0, 1, 1)
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage = QtWidgets.QComboBox(self.to_agglomerativeclustering)
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.setObjectName("comboBoxit_comboBox_clustering_agglomerativeclustering_linkage")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.addItem("")
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.addItem("")
        self.gridLayout_28.addWidget(self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage, 4, 1, 1, 2)
        self.stackedWidget_clustering.addWidget(self.to_agglomerativeclustering)
        self.to_DBSCAN = QtWidgets.QWidget()
        self.to_DBSCAN.setObjectName("to_DBSCAN")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.to_DBSCAN)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.label_35 = QtWidgets.QLabel(self.to_DBSCAN)
        self.label_35.setObjectName("label_35")
        self.gridLayout_29.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.to_DBSCAN)
        self.label_37.setObjectName("label_37")
        self.gridLayout_29.addWidget(self.label_37, 4, 0, 1, 1)
        self.lineEdi_clustering_DBSCAN_eps = QtWidgets.QLineEdit(self.to_DBSCAN)
        self.lineEdi_clustering_DBSCAN_eps.setObjectName("lineEdi_clustering_DBSCAN_eps")
        self.gridLayout_29.addWidget(self.lineEdi_clustering_DBSCAN_eps, 0, 1, 1, 1)
        self.lineEdi_clustering_DBSCAN_min_samples = QtWidgets.QLineEdit(self.to_DBSCAN)
        self.lineEdi_clustering_DBSCAN_min_samples.setObjectName("lineEdi_clustering_DBSCAN_min_samples")
        self.gridLayout_29.addWidget(self.lineEdi_clustering_DBSCAN_min_samples, 4, 1, 1, 1)
        self.stackedWidget_clustering.addWidget(self.to_DBSCAN)
        self.gridLayout_25.addWidget(self.stackedWidget_clustering, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.GroupBox_Settting_clustering, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.groupBox_methods = QtWidgets.QGroupBox(self.stackedWidgetPage_clustering)
        self.groupBox_methods.setObjectName("groupBox_methods")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_methods)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_hierarchical_clustering = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_hierarchical_clustering.setObjectName("radioButton_hierarchical_clustering")
        self.gridLayout_7.addWidget(self.radioButton_hierarchical_clustering, 2, 0, 1, 1)
        self.radioButton_spectral_clustering = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_spectral_clustering.setObjectName("radioButton_spectral_clustering")
        self.gridLayout_7.addWidget(self.radioButton_spectral_clustering, 1, 0, 1, 1)
        self.radioButton_clustering_kmeans = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_clustering_kmeans.setObjectName("radioButton_clustering_kmeans")
        self.gridLayout_7.addWidget(self.radioButton_clustering_kmeans, 0, 0, 1, 1)
        self.radioButton_DBSCAN = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_DBSCAN.setObjectName("radioButton_DBSCAN")
        self.gridLayout_7.addWidget(self.radioButton_DBSCAN, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_methods, 0, 0, 1, 2)
        self.stackedWidget_machine_learning_type.addWidget(self.stackedWidgetPage_clustering)
        self.stackedWidgetPage_deeplearning = QtWidgets.QWidget()
        self.stackedWidgetPage_deeplearning.setObjectName("stackedWidgetPage_deeplearning")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.stackedWidgetPage_deeplearning)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.stackedWidgetPage_deeplearning)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_RNN = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_RNN.setObjectName("radioButton_RNN")
        self.gridLayout_8.addWidget(self.radioButton_RNN, 2, 0, 1, 1)
        self.radioButton_GCN = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_GCN.setObjectName("radioButton_GCN")
        self.gridLayout_8.addWidget(self.radioButton_GCN, 1, 0, 1, 1)
        self.radioButton_CNN = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_CNN.setObjectName("radioButton_CNN")
        self.gridLayout_8.addWidget(self.radioButton_CNN, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.stackedWidgetPage_deeplearning)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_4.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.stackedWidget_machine_learning_type.addWidget(self.stackedWidgetPage_deeplearning)
        self.stackedWidgetPage_none = QtWidgets.QWidget()
        self.stackedWidgetPage_none.setObjectName("stackedWidgetPage_none")
        self.stackedWidget_machine_learning_type.addWidget(self.stackedWidgetPage_none)
        self.gridLayout_9.addWidget(self.stackedWidget_machine_learning_type, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 26))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menuConfiguration_file_F = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration_file_F.setObjectName("menuConfiguration_file_F")
        self.menuHelp_H = QtWidgets.QMenu(self.menubar)
        self.menuHelp_H.setObjectName("menuHelp_H")
        self.menuSkin = QtWidgets.QMenu(self.menubar)
        self.menuSkin.setObjectName("menuSkin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_configuration.setObjectName("actionLoad_configuration")
        self.actionSave_configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.actionWeb = QtWidgets.QAction(MainWindow)
        self.actionWeb.setObjectName("actionWeb")
        self.actionPDF = QtWidgets.QAction(MainWindow)
        self.actionPDF.setObjectName("actionPDF")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionDarkOrange = QtWidgets.QAction(MainWindow)
        self.actionDarkOrange.setObjectName("actionDarkOrange")
        self.actionGray = QtWidgets.QAction(MainWindow)
        self.actionGray.setObjectName("actionGray")
        self.actionBlue = QtWidgets.QAction(MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionNavy = QtWidgets.QAction(MainWindow)
        self.actionNavy.setObjectName("actionNavy")
        self.actionClassic = QtWidgets.QAction(MainWindow)
        self.actionClassic.setObjectName("actionClassic")
        self.actionGet_all_available_configuration = QtWidgets.QAction(MainWindow)
        self.actionGet_all_available_configuration.setObjectName("actionGet_all_available_configuration")
        self.menuConfiguration_file_F.addAction(self.actionLoad_configuration)
        self.menuConfiguration_file_F.addAction(self.actionSave_configuration)
        self.menuConfiguration_file_F.addAction(self.actionGet_all_available_configuration)
        self.menuHelp_H.addAction(self.actionWeb)
        self.menuHelp_H.addAction(self.actionPDF)
        self.menuSkin.addAction(self.actionDark)
        self.menuSkin.addAction(self.actionBlack)
        self.menuSkin.addAction(self.actionDarkOrange)
        self.menuSkin.addAction(self.actionGray)
        self.menuSkin.addAction(self.actionBlue)
        self.menuSkin.addAction(self.actionNavy)
        self.menuSkin.addAction(self.actionClassic)
        self.menubar.addAction(self.menuConfiguration_file_F.menuAction())
        self.menubar.addAction(self.menuHelp_H.menuAction())
        self.menubar.addAction(self.menuSkin.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_machine_learning_type.setCurrentIndex(0)
        self.stackedWidget_classification_setting.setCurrentIndex(7)
        self.stackedWidget_regression.setCurrentIndex(2)
        self.stackedWidget_clustering.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_machine_learning_type.setTitle(_translate("MainWindow", "Machine Learning Type"))
        self.radioButton_classification.setText(_translate("MainWindow", "Classification"))
        self.radioButton_regression.setText(_translate("MainWindow", "Regression"))
        self.radioButton_clustering.setText(_translate("MainWindow", "Clustering"))
        self.radioButton_deeplearning.setText(_translate("MainWindow", "Deep learning"))
        self.groupBox_method.setTitle(_translate("MainWindow", "Model"))
        self.radioButton_classification_gaussianprocess.setText(_translate("MainWindow", "GaussianProcessClassifier()"))
        self.radioButton_classification_randomforest.setText(_translate("MainWindow", "RandomForestClassifier()"))
        self.radioButton_classification_svm.setText(_translate("MainWindow", "SVC()"))
        self.radioButton_classification_lr.setText(_translate("MainWindow", "LogisticRegression(solver=\'saga\')"))
        self.radioButton_classification_adaboost.setText(_translate("MainWindow", "AdaBoostClassifier()"))
        self.radioButton_classification_ridge.setText(_translate("MainWindow", "RidgeClassifier()"))
        self.radioButton_classification_linearsvc.setText(_translate("MainWindow", "LinearSVC()"))
        self.groupBox_setting.setTitle(_translate("MainWindow", "Setting"))
        self.lineEdit_clf_lr_l1ratio.setText(_translate("MainWindow", "0.5"))
        self.comboBox_clf_lr_penalty.setItemText(0, _translate("MainWindow", "elasticnet"))
        self.comboBox_clf_lr_penalty.setItemText(1, _translate("MainWindow", "none"))
        self.label_2.setText(_translate("MainWindow", "L1_ratio"))
        self.label_8.setText(_translate("MainWindow", "Penalty"))
        self.label_12.setText(_translate("MainWindow", "C"))
        self.lineEdit_clf_lr_C.setText(_translate("MainWindow", "1"))
        self.comboBox_clf_linearsvc_multiclass.setItemText(0, _translate("MainWindow", "ovr"))
        self.comboBox_clf_linearsvc_multiclass.setItemText(1, _translate("MainWindow", "crammer_singer"))
        self.label_36.setText(_translate("MainWindow", "multi_class"))
        self.label_C_2.setText(_translate("MainWindow", "C"))
        self.lineEdit_clf_linearsvc_c.setText(_translate("MainWindow", "1"))
        self.label_gamma.setText(_translate("MainWindow", "Gamma"))
        self.label_C.setText(_translate("MainWindow", "C"))
        self.label_clf_svm_kernel.setText(_translate("MainWindow", "Kernel"))
        self.lineEdit_clf_svm_gamma.setText(_translate("MainWindow", "scale"))
        self.comboBox_clf_svm_kernel.setItemText(0, _translate("MainWindow", "linear"))
        self.comboBox_clf_svm_kernel.setItemText(1, _translate("MainWindow", "poly"))
        self.comboBox_clf_svm_kernel.setItemText(2, _translate("MainWindow", "rbf"))
        self.comboBox_clf_svm_kernel.setItemText(3, _translate("MainWindow", "sigmoid"))
        self.lineEdit_clf_svm_c.setText(_translate("MainWindow", "1"))
        self.label_20.setText(_translate("MainWindow", "Alpha"))
        self.lineEdit_clf_ridgeclf_alpha.setText(_translate("MainWindow", "1"))
        self.lineEdit_clf_gaussianprocess_kernel.setText(_translate("MainWindow", "None"))
        self.label_9.setText(_translate("MainWindow", "Multi_class"))
        self.label_10.setText(_translate("MainWindow", "Kernel"))
        self.comboBox_clf_gaussianprocess_multiclass.setItemText(0, _translate("MainWindow", "one_vs_rest"))
        self.comboBox_clf_gaussianprocess_multiclass.setItemText(1, _translate("MainWindow", "one_vs_one"))
        self.label_24.setText(_translate("MainWindow", "N_estimators"))
        self.label_23.setText(_translate("MainWindow", "Criterion"))
        self.label_26.setText(_translate("MainWindow", "Max_depth"))
        self.comboBox_clf_randomforest_criterion.setItemText(0, _translate("MainWindow", "gini"))
        self.comboBox_clf_randomforest_criterion.setItemText(1, _translate("MainWindow", "entropy"))
        self.lineEdit_clf_randomforest_maxdepth.setText(_translate("MainWindow", "None"))
        self.lineEdit_clf_randomforest_estimators.setText(_translate("MainWindow", "100"))
        self.comboBox_clf_adaboost_baseesitmator.setItemText(0, _translate("MainWindow", "DecisionTreeClassifier(max_depth=1)"))
        self.label_31.setText(_translate("MainWindow", "Base_estimator"))
        self.lineEdit_clf_adaboost_estimators.setText(_translate("MainWindow", "50"))
        self.label_29.setText(_translate("MainWindow", "Estimators"))
        self.label_7.setText(_translate("MainWindow", "Algorithm"))
        self.comboBox_clf_adaboost_algoritm.setItemText(0, _translate("MainWindow", "SAMME"))
        self.comboBox_clf_adaboost_algoritm.setItemText(1, _translate("MainWindow", "SAMME.R"))
        self.GroupBox_Settting.setTitle(_translate("MainWindow", "Setting"))
        self.label_11.setText(_translate("MainWindow", "Alpha"))
        self.lineEdit_regression_lasso_alpha.setText(_translate("MainWindow", "None"))
        self.label_17.setText(_translate("MainWindow", "L1_ratio"))
        self.label_28.setText(_translate("MainWindow", "Alpha"))
        self.lineEdit_regression_elasticnet_l1ratio.setText(_translate("MainWindow", "0.5"))
        self.lineEdit_regression_elasticnet_alpha.setText(_translate("MainWindow", "None"))
        self.comboBox_regression_svm_kernel.setItemText(0, _translate("MainWindow", "linear"))
        self.comboBox_regression_svm_kernel.setItemText(1, _translate("MainWindow", "poly"))
        self.comboBox_regression_svm_kernel.setItemText(2, _translate("MainWindow", "rbf"))
        self.comboBox_regression_svm_kernel.setItemText(3, _translate("MainWindow", "sigmoid"))
        self.label_3.setText(_translate("MainWindow", "C"))
        self.label.setText(_translate("MainWindow", "Kernel"))
        self.lineEdit_regression_svm_gamma.setText(_translate("MainWindow", "scale"))
        self.label_4.setText(_translate("MainWindow", "Gamma"))
        self.lineEdit_regression_svm_c.setText(_translate("MainWindow", "1"))
        self.label_5.setText(_translate("MainWindow", "Alpha"))
        self.label_6.setText(_translate("MainWindow", "Kernel"))
        self.lineEdit_regression_gaussianprocess_alpha.setText(_translate("MainWindow", "1e-10"))
        self.lineEdit_regression_gaussianprocess_kernel.setText(_translate("MainWindow", "None"))
        self.label_30.setText(_translate("MainWindow", "Criterion"))
        self.comboBox_regression_randomforest_criterion.setItemText(0, _translate("MainWindow", "mse"))
        self.comboBox_regression_randomforest_criterion.setItemText(1, _translate("MainWindow", "mae"))
        self.label_25.setText(_translate("MainWindow", "N_estimators"))
        self.lineEdit_regression_randomforest_estimators.setText(_translate("MainWindow", "100"))
        self.label_27.setText(_translate("MainWindow", "Max_depth"))
        self.lineEdit_regression_randomforest_maxdepth.setText(_translate("MainWindow", "None"))
        self.Methods.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_regression_gaussianprocess.setText(_translate("MainWindow", "GaussianProcessRegressor()"))
        self.radioButton_regression_lasso.setText(_translate("MainWindow", "LassoCV()"))
        self.radioButton_regression_randomforest.setText(_translate("MainWindow", "RandomForestRegressor()"))
        self.radioButton_regression_ridge.setText(_translate("MainWindow", "RidgeCV()"))
        self.radioButton_regression_linearregression.setText(_translate("MainWindow", "LinearRegression()"))
        self.radioButton_regression_svm.setText(_translate("MainWindow", "SVR()"))
        self.radioButton_regression_elasticnet.setText(_translate("MainWindow", "ElasticNetCV()"))
        self.GroupBox_Settting_clustering.setTitle(_translate("MainWindow", "Setting"))
        self.label_13.setText(_translate("MainWindow", "n_clusters"))
        self.label_14.setText(_translate("MainWindow", "init"))
        self.label_16.setText(_translate("MainWindow", "n_init"))
        self.lineEdit_clustering_kmeans_n_init.setText(_translate("MainWindow", "10"))
        self.label_18.setText(_translate("MainWindow", "random_state"))
        self.comboBox_clustering_kmeans_init.setItemText(0, _translate("MainWindow", "k-means++"))
        self.comboBox_clustering_kmeans_init.setItemText(1, _translate("MainWindow", "random"))
        self.label_21.setText(_translate("MainWindow", "n_clusters"))
        self.label_22.setText(_translate("MainWindow", "n_init"))
        self.lineEdit_clustering_kmeans_n_init_2.setText(_translate("MainWindow", "10"))
        self.label_19.setText(_translate("MainWindow", "random_state"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.setItemText(0, _translate("MainWindow", "euclidean"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.setItemText(1, _translate("MainWindow", "l1"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.setItemText(2, _translate("MainWindow", "l2"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.setItemText(3, _translate("MainWindow", "manhattan"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_affinity.setItemText(4, _translate("MainWindow", "cosine"))
        self.label_34.setText(_translate("MainWindow", "n_clusters"))
        self.label_32.setText(_translate("MainWindow", "affinity"))
        self.label_33.setText(_translate("MainWindow", "linkage"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.setItemText(0, _translate("MainWindow", "ward"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.setItemText(1, _translate("MainWindow", "complete"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.setItemText(2, _translate("MainWindow", "average"))
        self.comboBoxit_comboBox_clustering_agglomerativeclustering_linkage.setItemText(3, _translate("MainWindow", "single"))
        self.label_35.setText(_translate("MainWindow", "eps"))
        self.label_37.setText(_translate("MainWindow", "min_samples"))
        self.lineEdi_clustering_DBSCAN_eps.setText(_translate("MainWindow", "0.5"))
        self.lineEdi_clustering_DBSCAN_min_samples.setText(_translate("MainWindow", "5"))
        self.groupBox_methods.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_hierarchical_clustering.setText(_translate("MainWindow", "AgglomerativeClustering()"))
        self.radioButton_spectral_clustering.setText(_translate("MainWindow", "SpectralClustering()"))
        self.radioButton_clustering_kmeans.setText(_translate("MainWindow", "KMeans()"))
        self.radioButton_DBSCAN.setText(_translate("MainWindow", "DBSCAN()"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_RNN.setText(_translate("MainWindow", "RNN"))
        self.radioButton_GCN.setText(_translate("MainWindow", "GCN"))
        self.radioButton_CNN.setText(_translate("MainWindow", "CNN"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Setting"))
        self.menuConfiguration_file_F.setTitle(_translate("MainWindow", "Configuration file(&F)"))
        self.menuHelp_H.setTitle(_translate("MainWindow", "Help(&H)"))
        self.menuSkin.setTitle(_translate("MainWindow", "Skin"))
        self.actionLoad_configuration.setText(_translate("MainWindow", "Load configuration"))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save configuration"))
        self.actionWeb.setText(_translate("MainWindow", "Web"))
        self.actionPDF.setText(_translate("MainWindow", "PDF"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionDarkOrange.setText(_translate("MainWindow", "DarkOrange"))
        self.actionGray.setText(_translate("MainWindow", "Gray"))
        self.actionBlue.setText(_translate("MainWindow", "Blue"))
        self.actionNavy.setText(_translate("MainWindow", "Navy"))
        self.actionClassic.setText(_translate("MainWindow", "Classic"))
        self.actionGet_all_available_configuration.setText(_translate("MainWindow", "Get all available configuration"))
