# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './easylearn_feature_engineering_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 727)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.tabWidget_items = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_items.sizePolicy().hasHeightForWidth())
        self.tabWidget_items.setSizePolicy(sizePolicy)
        self.tabWidget_items.setMinimumSize(QtCore.QSize(100, 100))
        self.tabWidget_items.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_items.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_items.setObjectName("tabWidget_items")
        self.tabWidget_itemsPage1 = QtWidgets.QWidget()
        self.tabWidget_itemsPage1.setObjectName("tabWidget_itemsPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.tabWidget_itemsPage1)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.groupBox_preprocessing_setting = QtWidgets.QGroupBox(self.tabWidget_itemsPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_preprocessing_setting.sizePolicy().hasHeightForWidth())
        self.groupBox_preprocessing_setting.setSizePolicy(sizePolicy)
        self.groupBox_preprocessing_setting.setMinimumSize(QtCore.QSize(300, 80))
        self.groupBox_preprocessing_setting.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.groupBox_preprocessing_setting.setObjectName("groupBox_preprocessing_setting")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_preprocessing_setting)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.stackedWidget_preprocessing_methods = QtWidgets.QStackedWidget(self.groupBox_preprocessing_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_preprocessing_methods.sizePolicy().hasHeightForWidth())
        self.stackedWidget_preprocessing_methods.setSizePolicy(sizePolicy)
        self.stackedWidget_preprocessing_methods.setObjectName("stackedWidget_preprocessing_methods")
        self.to_zscore = QtWidgets.QWidget()
        self.to_zscore.setObjectName("to_zscore")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.to_zscore)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_zscore = QtWidgets.QLabel(self.to_zscore)
        self.label_zscore.setText("")
        self.label_zscore.setObjectName("label_zscore")
        self.gridLayout_17.addWidget(self.label_zscore, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_zscore)
        self.to_scaling = QtWidgets.QWidget()
        self.to_scaling.setObjectName("to_scaling")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.to_scaling)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEdit_scaling_min = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit_scaling_min.setObjectName("lineEdit_scaling_min")
        self.gridLayout_10.addWidget(self.lineEdit_scaling_min, 1, 1, 1, 1)
        self.label_scaling_max = QtWidgets.QLabel(self.to_scaling)
        self.label_scaling_max.setObjectName("label_scaling_max")
        self.gridLayout_10.addWidget(self.label_scaling_max, 0, 0, 1, 1)
        self.lineEdit_scaling_max = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit_scaling_max.setObjectName("lineEdit_scaling_max")
        self.gridLayout_10.addWidget(self.lineEdit_scaling_max, 0, 1, 1, 1)
        self.label_scaling_min = QtWidgets.QLabel(self.to_scaling)
        self.label_scaling_min.setObjectName("label_scaling_min")
        self.gridLayout_10.addWidget(self.label_scaling_min, 1, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_scaling)
        self.to_none = QtWidgets.QWidget()
        self.to_none.setObjectName("to_none")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.to_none)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_none = QtWidgets.QLabel(self.to_none)
        self.label_none.setText("")
        self.label_none.setObjectName("label_none")
        self.gridLayout_19.addWidget(self.label_none, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_none)
        self.gridLayout_26.addWidget(self.stackedWidget_preprocessing_methods, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_preprocessing_setting, 0, 2, 1, 1)
        self.groupBox_preprocessing_method = QtWidgets.QGroupBox(self.tabWidget_itemsPage1)
        self.groupBox_preprocessing_method.setObjectName("groupBox_preprocessing_method")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_preprocessing_method)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_none_methods = QtWidgets.QRadioButton(self.groupBox_preprocessing_method)
        self.radioButton_none_methods.setObjectName("radioButton_none_methods")
        self.gridLayout_8.addWidget(self.radioButton_none_methods, 2, 0, 1, 1)
        self.radioButton_zscore = QtWidgets.QRadioButton(self.groupBox_preprocessing_method)
        self.radioButton_zscore.setObjectName("radioButton_zscore")
        self.gridLayout_8.addWidget(self.radioButton_zscore, 0, 0, 1, 1)
        self.radioButton_scaling = QtWidgets.QRadioButton(self.groupBox_preprocessing_method)
        self.radioButton_scaling.setObjectName("radioButton_scaling")
        self.gridLayout_8.addWidget(self.radioButton_scaling, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_preprocessing_method, 0, 0, 1, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage1, "")
        self.tabWidget_itemsPage2 = QtWidgets.QWidget()
        self.tabWidget_itemsPage2.setObjectName("tabWidget_itemsPage2")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tabWidget_itemsPage2)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBox_dimension_reduction = QtWidgets.QGroupBox(self.tabWidget_itemsPage2)
        self.groupBox_dimension_reduction.setObjectName("groupBox_dimension_reduction")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox_dimension_reduction)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.radioButton_lda = QtWidgets.QRadioButton(self.groupBox_dimension_reduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_lda.sizePolicy().hasHeightForWidth())
        self.radioButton_lda.setSizePolicy(sizePolicy)
        self.radioButton_lda.setObjectName("radioButton_lda")
        self.gridLayout_28.addWidget(self.radioButton_lda, 2, 0, 1, 1)
        self.radioButton_nmf = QtWidgets.QRadioButton(self.groupBox_dimension_reduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_nmf.sizePolicy().hasHeightForWidth())
        self.radioButton_nmf.setSizePolicy(sizePolicy)
        self.radioButton_nmf.setObjectName("radioButton_nmf")
        self.gridLayout_28.addWidget(self.radioButton_nmf, 1, 0, 1, 1)
        self.radioButton_pca = QtWidgets.QRadioButton(self.groupBox_dimension_reduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_pca.sizePolicy().hasHeightForWidth())
        self.radioButton_pca.setSizePolicy(sizePolicy)
        self.radioButton_pca.setObjectName("radioButton_pca")
        self.gridLayout_28.addWidget(self.radioButton_pca, 0, 0, 1, 1)
        self.radioButton_none = QtWidgets.QRadioButton(self.groupBox_dimension_reduction)
        self.radioButton_none.setObjectName("radioButton_none")
        self.gridLayout_28.addWidget(self.radioButton_none, 3, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_dimension_reduction, 0, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.tabWidget_itemsPage2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_29.addWidget(self.label, 0, 2, 1, 1)
        self.groupBox_dimreduction_setting = QtWidgets.QGroupBox(self.tabWidget_itemsPage2)
        self.groupBox_dimreduction_setting.setObjectName("groupBox_dimreduction_setting")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_dimreduction_setting)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget_dimreduction = QtWidgets.QStackedWidget(self.groupBox_dimreduction_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_dimreduction.sizePolicy().hasHeightForWidth())
        self.stackedWidget_dimreduction.setSizePolicy(sizePolicy)
        self.stackedWidget_dimreduction.setObjectName("stackedWidget_dimreduction")
        self.to_pca = QtWidgets.QWidget()
        self.to_pca.setObjectName("to_pca")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.to_pca)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_pca_components = QtWidgets.QLabel(self.to_pca)
        self.label_pca_components.setObjectName("label_pca_components")
        self.gridLayout_11.addWidget(self.label_pca_components, 0, 0, 1, 1)
        self.lineEdit_pca_components = QtWidgets.QLineEdit(self.to_pca)
        self.lineEdit_pca_components.setObjectName("lineEdit_pca_components")
        self.gridLayout_11.addWidget(self.lineEdit_pca_components, 0, 2, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_pca)
        self.to_lda = QtWidgets.QWidget()
        self.to_lda.setObjectName("to_lda")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.to_lda)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_ida_components = QtWidgets.QLabel(self.to_lda)
        self.label_ida_components.setObjectName("label_ida_components")
        self.gridLayout_13.addWidget(self.label_ida_components, 0, 0, 1, 1)
        self.lineEdit_ida_components = QtWidgets.QLineEdit(self.to_lda)
        self.lineEdit_ida_components.setObjectName("lineEdit_ida_components")
        self.gridLayout_13.addWidget(self.lineEdit_ida_components, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_lda)
        self.to_nmf = QtWidgets.QWidget()
        self.to_nmf.setObjectName("to_nmf")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.to_nmf)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.lineEdit_nmf_components = QtWidgets.QLineEdit(self.to_nmf)
        self.lineEdit_nmf_components.setObjectName("lineEdit_nmf_components")
        self.gridLayout_21.addWidget(self.lineEdit_nmf_components, 0, 1, 1, 1)
        self.label_nmf_components = QtWidgets.QLabel(self.to_nmf)
        self.label_nmf_components.setObjectName("label_nmf_components")
        self.gridLayout_21.addWidget(self.label_nmf_components, 0, 0, 1, 1)
        self.label_nmf_init = QtWidgets.QLabel(self.to_nmf)
        self.label_nmf_init.setObjectName("label_nmf_init")
        self.gridLayout_21.addWidget(self.label_nmf_init, 1, 0, 1, 1)
        self.comboBox_nmf_init = QtWidgets.QComboBox(self.to_nmf)
        self.comboBox_nmf_init.setObjectName("comboBox_nmf_init")
        self.comboBox_nmf_init.addItem("")
        self.gridLayout_21.addWidget(self.comboBox_nmf_init, 1, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_nmf)
        self.to_none_dimreduction = QtWidgets.QWidget()
        self.to_none_dimreduction.setObjectName("to_none_dimreduction")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.to_none_dimreduction)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget_dimreduction.addWidget(self.to_none_dimreduction)
        self.gridLayout_3.addWidget(self.stackedWidget_dimreduction, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_dimreduction_setting, 0, 1, 2, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage2, "")
        self.tabWidget_itemsPage3 = QtWidgets.QWidget()
        self.tabWidget_itemsPage3.setObjectName("tabWidget_itemsPage3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tabWidget_itemsPage3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabWidget_itemsPage3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_filter = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter.sizePolicy().hasHeightForWidth())
        self.label_filter.setSizePolicy(sizePolicy)
        self.label_filter.setObjectName("label_filter")
        self.gridLayout_4.addWidget(self.label_filter, 0, 0, 1, 1)
        self.radioButton_variance_threshold = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_variance_threshold.setObjectName("radioButton_variance_threshold")
        self.gridLayout_4.addWidget(self.radioButton_variance_threshold, 1, 0, 1, 1)
        self.radioButton_correlation = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_correlation.setObjectName("radioButton_correlation")
        self.gridLayout_4.addWidget(self.radioButton_correlation, 2, 0, 1, 1)
        self.radioButton_distancecorrelation = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_distancecorrelation.setObjectName("radioButton_distancecorrelation")
        self.gridLayout_4.addWidget(self.radioButton_distancecorrelation, 3, 0, 1, 1)
        self.radioButton_fscore = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_fscore.setObjectName("radioButton_fscore")
        self.gridLayout_4.addWidget(self.radioButton_fscore, 4, 0, 1, 1)
        self.radioButton_mutualinfo_cls = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_mutualinfo_cls.setObjectName("radioButton_mutualinfo_cls")
        self.gridLayout_4.addWidget(self.radioButton_mutualinfo_cls, 5, 0, 1, 1)
        self.radioButton_mutualinfo_regression = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_mutualinfo_regression.setObjectName("radioButton_mutualinfo_regression")
        self.gridLayout_4.addWidget(self.radioButton_mutualinfo_regression, 6, 0, 1, 1)
        self.radioButton_relieff = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_relieff.setObjectName("radioButton_relieff")
        self.gridLayout_4.addWidget(self.radioButton_relieff, 7, 0, 1, 1)
        self.radioButton_anova = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_anova.setObjectName("radioButton_anova")
        self.gridLayout_4.addWidget(self.radioButton_anova, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 9, 0, 1, 1)
        self.label_wrapper = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_wrapper.sizePolicy().hasHeightForWidth())
        self.label_wrapper.setSizePolicy(sizePolicy)
        self.label_wrapper.setObjectName("label_wrapper")
        self.gridLayout_4.addWidget(self.label_wrapper, 10, 0, 1, 1)
        self.radioButton_rfe = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_rfe.setObjectName("radioButton_rfe")
        self.gridLayout_4.addWidget(self.radioButton_rfe, 11, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 12, 0, 1, 1)
        self.label_embedded = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_embedded.sizePolicy().hasHeightForWidth())
        self.label_embedded.setSizePolicy(sizePolicy)
        self.label_embedded.setObjectName("label_embedded")
        self.gridLayout_4.addWidget(self.label_embedded, 13, 0, 1, 1)
        self.radioButton_l1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_l1.setObjectName("radioButton_l1")
        self.gridLayout_4.addWidget(self.radioButton_l1, 14, 0, 1, 1)
        self.radioButton_elasticnet = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_elasticnet.setObjectName("radioButton_elasticnet")
        self.gridLayout_4.addWidget(self.radioButton_elasticnet, 15, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 16, 0, 1, 1)
        self.radioButton_featureselection_none = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_featureselection_none.setObjectName("radioButton_featureselection_none")
        self.gridLayout_4.addWidget(self.radioButton_featureselection_none, 17, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 18, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_3, 0, 0, 2, 2)
        self.groupBox_feature_selection_setting = QtWidgets.QGroupBox(self.tabWidget_itemsPage3)
        self.groupBox_feature_selection_setting.setObjectName("groupBox_feature_selection_setting")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_feature_selection_setting)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.stackedWidget_feature_selection = QtWidgets.QStackedWidget(self.groupBox_feature_selection_setting)
        self.stackedWidget_feature_selection.setObjectName("stackedWidget_feature_selection")
        self.to_variance_threshold = QtWidgets.QWidget()
        self.to_variance_threshold.setObjectName("to_variance_threshold")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.to_variance_threshold)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_variancethreshold_threshold = QtWidgets.QLabel(self.to_variance_threshold)
        self.label_variancethreshold_threshold.setObjectName("label_variancethreshold_threshold")
        self.gridLayout_15.addWidget(self.label_variancethreshold_threshold, 0, 0, 1, 1)
        self.lineEdit_variancethreshold_threshold = QtWidgets.QLineEdit(self.to_variance_threshold)
        self.lineEdit_variancethreshold_threshold.setObjectName("lineEdit_variancethreshold_threshold")
        self.gridLayout_15.addWidget(self.lineEdit_variancethreshold_threshold, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_variance_threshold)
        self.correlation = QtWidgets.QWidget()
        self.correlation.setObjectName("correlation")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.correlation)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_correlation_abscoef = QtWidgets.QLabel(self.correlation)
        self.label_correlation_abscoef.setObjectName("label_correlation_abscoef")
        self.gridLayout_16.addWidget(self.label_correlation_abscoef, 0, 0, 1, 1)
        self.lineEdit_correlation_abscoef = QtWidgets.QLineEdit(self.correlation)
        self.lineEdit_correlation_abscoef.setObjectName("lineEdit_correlation_abscoef")
        self.gridLayout_16.addWidget(self.lineEdit_correlation_abscoef, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.correlation)
        self.to_distancecorrelation = QtWidgets.QWidget()
        self.to_distancecorrelation.setObjectName("to_distancecorrelation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.to_distancecorrelation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_distancecorrelation_abscoef = QtWidgets.QLabel(self.to_distancecorrelation)
        self.label_distancecorrelation_abscoef.setObjectName("label_distancecorrelation_abscoef")
        self.gridLayout_2.addWidget(self.label_distancecorrelation_abscoef, 0, 0, 1, 1)
        self.lineEdit_distancecorrelation_abscoef = QtWidgets.QLineEdit(self.to_distancecorrelation)
        self.lineEdit_distancecorrelation_abscoef.setObjectName("lineEdit_distancecorrelation_abscoef")
        self.gridLayout_2.addWidget(self.lineEdit_distancecorrelation_abscoef, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_distancecorrelation)
        self.to_fscore = QtWidgets.QWidget()
        self.to_fscore.setObjectName("to_fscore")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.to_fscore)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_fscore_topnum = QtWidgets.QLabel(self.to_fscore)
        self.label_fscore_topnum.setObjectName("label_fscore_topnum")
        self.gridLayout_14.addWidget(self.label_fscore_topnum, 0, 0, 1, 1)
        self.lineEdit_fscore_topnum = QtWidgets.QLineEdit(self.to_fscore)
        self.lineEdit_fscore_topnum.setObjectName("lineEdit_fscore_topnum")
        self.gridLayout_14.addWidget(self.lineEdit_fscore_topnum, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_fscore)
        self.to_mutualinfo_cls = QtWidgets.QWidget()
        self.to_mutualinfo_cls.setObjectName("to_mutualinfo_cls")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.to_mutualinfo_cls)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_mutualinfocls_topnum = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_mutualinfocls_topnum.setObjectName("label_mutualinfocls_topnum")
        self.gridLayout_22.addWidget(self.label_mutualinfocls_topnum, 2, 0, 1, 1)
        self.label_mutualinfo_cls = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_mutualinfo_cls.setObjectName("label_mutualinfo_cls")
        self.gridLayout_22.addWidget(self.label_mutualinfo_cls, 4, 0, 1, 1)
        self.spinBox_mutualinfocls_neighbors = QtWidgets.QSpinBox(self.to_mutualinfo_cls)
        self.spinBox_mutualinfocls_neighbors.setProperty("value", 3)
        self.spinBox_mutualinfocls_neighbors.setObjectName("spinBox_mutualinfocls_neighbors")
        self.gridLayout_22.addWidget(self.spinBox_mutualinfocls_neighbors, 4, 1, 1, 1)
        self.lineEdit_mutualinfocls_topnum = QtWidgets.QLineEdit(self.to_mutualinfo_cls)
        self.lineEdit_mutualinfocls_topnum.setObjectName("lineEdit_mutualinfocls_topnum")
        self.gridLayout_22.addWidget(self.lineEdit_mutualinfocls_topnum, 2, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_mutualinfo_cls)
        self.to_mutualinfo_regression = QtWidgets.QWidget()
        self.to_mutualinfo_regression.setObjectName("to_mutualinfo_regression")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.to_mutualinfo_regression)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.spinBox_mutualinforeg_neighbors = QtWidgets.QSpinBox(self.to_mutualinfo_regression)
        self.spinBox_mutualinforeg_neighbors.setProperty("value", 3)
        self.spinBox_mutualinforeg_neighbors.setObjectName("spinBox_mutualinforeg_neighbors")
        self.gridLayout_12.addWidget(self.spinBox_mutualinforeg_neighbors, 2, 1, 1, 1)
        self.label_mutualinforeg_topnum = QtWidgets.QLabel(self.to_mutualinfo_regression)
        self.label_mutualinforeg_topnum.setObjectName("label_mutualinforeg_topnum")
        self.gridLayout_12.addWidget(self.label_mutualinforeg_topnum, 2, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.to_mutualinfo_regression)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_mutualinforeg_topnum = QtWidgets.QLineEdit(self.to_mutualinfo_regression)
        self.lineEdit_mutualinforeg_topnum.setObjectName("lineEdit_mutualinforeg_topnum")
        self.gridLayout_12.addWidget(self.lineEdit_mutualinforeg_topnum, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_mutualinfo_regression)
        self.to_reliff = QtWidgets.QWidget()
        self.to_reliff.setObjectName("to_reliff")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.to_reliff)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.lineEdit_relieff_topnum = QtWidgets.QLineEdit(self.to_reliff)
        self.lineEdit_relieff_topnum.setObjectName("lineEdit_relieff_topnum")
        self.gridLayout_18.addWidget(self.lineEdit_relieff_topnum, 0, 1, 1, 1)
        self.label_reliffmin = QtWidgets.QLabel(self.to_reliff)
        self.label_reliffmin.setObjectName("label_reliffmin")
        self.gridLayout_18.addWidget(self.label_reliffmin, 0, 0, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_reliff)
        self.to_anova = QtWidgets.QWidget()
        self.to_anova.setObjectName("to_anova")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.to_anova)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_11 = QtWidgets.QLabel(self.to_anova)
        self.label_11.setObjectName("label_11")
        self.gridLayout_23.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.to_anova)
        self.label_17.setObjectName("label_17")
        self.gridLayout_23.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_anova_topnum = QtWidgets.QLineEdit(self.to_anova)
        self.lineEdit_anova_topnum.setObjectName("lineEdit_anova_topnum")
        self.gridLayout_23.addWidget(self.lineEdit_anova_topnum, 0, 2, 1, 1)
        self.comboBox_anova_multicorrect = QtWidgets.QComboBox(self.to_anova)
        self.comboBox_anova_multicorrect.setObjectName("comboBox_anova_multicorrect")
        self.comboBox_anova_multicorrect.addItem("")
        self.comboBox_anova_multicorrect.addItem("")
        self.comboBox_anova_multicorrect.addItem("")
        self.gridLayout_23.addWidget(self.comboBox_anova_multicorrect, 2, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_anova)
        self.to_rfe = QtWidgets.QWidget()
        self.to_rfe.setObjectName("to_rfe")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.to_rfe)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_19 = QtWidgets.QLabel(self.to_rfe)
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 3, 0, 1, 1)
        self.spinBox_rfe_nfold = QtWidgets.QSpinBox(self.to_rfe)
        self.spinBox_rfe_nfold.setMinimum(2)
        self.spinBox_rfe_nfold.setMaximum(1000)
        self.spinBox_rfe_nfold.setProperty("value", 5)
        self.spinBox_rfe_nfold.setObjectName("spinBox_rfe_nfold")
        self.gridLayout_20.addWidget(self.spinBox_rfe_nfold, 1, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.to_rfe)
        self.label_16.setObjectName("label_16")
        self.gridLayout_20.addWidget(self.label_16, 2, 0, 1, 1)
        self.comboBox_rfe_estimator = QtWidgets.QComboBox(self.to_rfe)
        self.comboBox_rfe_estimator.setObjectName("comboBox_rfe_estimator")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.gridLayout_20.addWidget(self.comboBox_rfe_estimator, 2, 2, 1, 1)
        self.spinBox_rfe_njobs = QtWidgets.QSpinBox(self.to_rfe)
        self.spinBox_rfe_njobs.setMinimum(-1)
        self.spinBox_rfe_njobs.setProperty("value", -1)
        self.spinBox_rfe_njobs.setObjectName("spinBox_rfe_njobs")
        self.gridLayout_20.addWidget(self.spinBox_rfe_njobs, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.to_rfe)
        self.label_15.setObjectName("label_15")
        self.gridLayout_20.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.to_rfe)
        self.label_14.setObjectName("label_14")
        self.gridLayout_20.addWidget(self.label_14, 0, 0, 1, 1)
        self.doubleSpinBox_rfe_step = QtWidgets.QDoubleSpinBox(self.to_rfe)
        self.doubleSpinBox_rfe_step.setMaximum(10000.0)
        self.doubleSpinBox_rfe_step.setSingleStep(0.1)
        self.doubleSpinBox_rfe_step.setProperty("value", 0.1)
        self.doubleSpinBox_rfe_step.setObjectName("doubleSpinBox_rfe_step")
        self.gridLayout_20.addWidget(self.doubleSpinBox_rfe_step, 0, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_rfe)
        self.to_l1 = QtWidgets.QWidget()
        self.to_l1.setObjectName("to_l1")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.to_l1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_40 = QtWidgets.QLabel(self.to_l1)
        self.label_40.setObjectName("label_40")
        self.gridLayout_24.addWidget(self.label_40, 0, 0, 1, 1)
        self.lineEdit_l1_alpha = QtWidgets.QLineEdit(self.to_l1)
        self.lineEdit_l1_alpha.setObjectName("lineEdit_l1_alpha")
        self.gridLayout_24.addWidget(self.lineEdit_l1_alpha, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_l1)
        self.to_elasticnet = QtWidgets.QWidget()
        self.to_elasticnet.setObjectName("to_elasticnet")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.to_elasticnet)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_46 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_46.setObjectName("label_46")
        self.gridLayout_25.addWidget(self.label_46, 2, 0, 1, 1)
        self.lineEdit_elasticnet_l1ratio = QtWidgets.QLineEdit(self.to_elasticnet)
        self.lineEdit_elasticnet_l1ratio.setObjectName("lineEdit_elasticnet_l1ratio")
        self.gridLayout_25.addWidget(self.lineEdit_elasticnet_l1ratio, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_44.setObjectName("label_44")
        self.gridLayout_25.addWidget(self.label_44, 0, 0, 1, 1)
        self.lineEdit_elasticnet_alpha = QtWidgets.QLineEdit(self.to_elasticnet)
        self.lineEdit_elasticnet_alpha.setObjectName("lineEdit_elasticnet_alpha")
        self.gridLayout_25.addWidget(self.lineEdit_elasticnet_alpha, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_elasticnet)
        self.to_none_featureselection = QtWidgets.QWidget()
        self.to_none_featureselection.setObjectName("to_none_featureselection")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.to_none_featureselection)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_none_featureselection = QtWidgets.QLabel(self.to_none_featureselection)
        self.label_none_featureselection.setText("")
        self.label_none_featureselection.setObjectName("label_none_featureselection")
        self.gridLayout_27.addWidget(self.label_none_featureselection, 0, 0, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_none_featureselection)
        self.gridLayout_9.addWidget(self.stackedWidget_feature_selection, 0, 1, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_feature_selection_setting, 0, 2, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem1, 1, 1, 1, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage3, "")
        self.tabWidget_itemsPage4 = QtWidgets.QWidget()
        self.tabWidget_itemsPage4.setObjectName("tabWidget_itemsPage4")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tabWidget_itemsPage4)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabWidget_itemsPage4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_extractionunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_extractionunder.setObjectName("radioButton_extractionunder")
        self.gridLayout_7.addWidget(self.radioButton_extractionunder, 8, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 5, 0, 1, 1)
        self.radioButton_smotencover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_smotencover.setObjectName("radioButton_smotencover")
        self.gridLayout_7.addWidget(self.radioButton_smotencover, 3, 0, 1, 1)
        self.radioButton_nearmissunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_nearmissunder.setObjectName("radioButton_nearmissunder")
        self.gridLayout_7.addWidget(self.radioButton_nearmissunder, 10, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.radioButton_randunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_randunder.setObjectName("radioButton_randunder")
        self.gridLayout_7.addWidget(self.radioButton_randunder, 7, 0, 1, 1)
        self.radioButton_bsmoteover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_bsmoteover.setObjectName("radioButton_bsmoteover")
        self.gridLayout_7.addWidget(self.radioButton_bsmoteover, 4, 0, 1, 1)
        self.radioButton_randover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_randover.setCheckable(True)
        self.radioButton_randover.setChecked(False)
        self.radioButton_randover.setObjectName("radioButton_randover")
        self.gridLayout_7.addWidget(self.radioButton_randover, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 6, 0, 1, 1)
        self.radioButton_smoteover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_smoteover.setObjectName("radioButton_smoteover")
        self.gridLayout_7.addWidget(self.radioButton_smoteover, 2, 0, 1, 1)
        self.radioButton_cludterunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_cludterunder.setObjectName("radioButton_cludterunder")
        self.gridLayout_7.addWidget(self.radioButton_cludterunder, 9, 0, 1, 1)
        self.gridLayout_31.addWidget(self.groupBox_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabWidget_itemsPage4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_31.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage4, "")
        self.gridLayout_32.addWidget(self.tabWidget_items, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 26))
        self.menubar.setObjectName("menubar")
        self.menuConfiguration_file_f = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration_file_f.setObjectName("menuConfiguration_file_f")
        self.menuHelp_G = QtWidgets.QMenu(self.menubar)
        self.menuHelp_G.setObjectName("menuHelp_G")
        self.menuSkin = QtWidgets.QMenu(self.menubar)
        self.menuSkin.setObjectName("menuSkin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_configuration.setObjectName("actionLoad_configuration")
        self.actionSave_configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionDarkOrange = QtWidgets.QAction(MainWindow)
        self.actionDarkOrange.setObjectName("actionDarkOrange")
        self.actionGray = QtWidgets.QAction(MainWindow)
        self.actionGray.setObjectName("actionGray")
        self.actionBlue = QtWidgets.QAction(MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionNavy = QtWidgets.QAction(MainWindow)
        self.actionNavy.setObjectName("actionNavy")
        self.actionClassic = QtWidgets.QAction(MainWindow)
        self.actionClassic.setObjectName("actionClassic")
        self.actionGet_all_available_configuraton = QtWidgets.QAction(MainWindow)
        self.actionGet_all_available_configuraton.setObjectName("actionGet_all_available_configuraton")
        self.menuConfiguration_file_f.addAction(self.actionLoad_configuration)
        self.menuConfiguration_file_f.addAction(self.actionSave_configuration)
        self.menuConfiguration_file_f.addAction(self.actionGet_all_available_configuraton)
        self.menuSkin.addAction(self.actionDark)
        self.menuSkin.addAction(self.actionBlack)
        self.menuSkin.addAction(self.actionDarkOrange)
        self.menuSkin.addAction(self.actionGray)
        self.menuSkin.addAction(self.actionBlue)
        self.menuSkin.addAction(self.actionNavy)
        self.menuSkin.addAction(self.actionClassic)
        self.menubar.addAction(self.menuConfiguration_file_f.menuAction())
        self.menubar.addAction(self.menuHelp_G.menuAction())
        self.menubar.addAction(self.menuSkin.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_items.setCurrentIndex(0)
        self.stackedWidget_preprocessing_methods.setCurrentIndex(2)
        self.stackedWidget_dimreduction.setCurrentIndex(1)
        self.stackedWidget_feature_selection.setCurrentIndex(11)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_preprocessing_setting.setTitle(_translate("MainWindow", "Setting"))
        self.lineEdit_scaling_min.setText(_translate("MainWindow", "0"))
        self.label_scaling_max.setText(_translate("MainWindow", "Max"))
        self.lineEdit_scaling_max.setText(_translate("MainWindow", "1"))
        self.label_scaling_min.setText(_translate("MainWindow", "Min"))
        self.groupBox_preprocessing_method.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_none_methods.setText(_translate("MainWindow", "None"))
        self.radioButton_zscore.setText(_translate("MainWindow", "Z-score normalization"))
        self.radioButton_scaling.setText(_translate("MainWindow", "Scaling"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage1), _translate("MainWindow", "  Preprocessing  "))
        self.groupBox_dimension_reduction.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_lda.setText(_translate("MainWindow", "Latent Dirichlet Allocation"))
        self.radioButton_nmf.setText(_translate("MainWindow", "Non-negative matrix factorization"))
        self.radioButton_pca.setText(_translate("MainWindow", "Principal component analysis"))
        self.radioButton_none.setText(_translate("MainWindow", "None"))
        self.groupBox_dimreduction_setting.setTitle(_translate("MainWindow", "Setting"))
        self.label_pca_components.setText(_translate("MainWindow", "Components"))
        self.lineEdit_pca_components.setText(_translate("MainWindow", "0.80, 0.90"))
        self.label_ida_components.setText(_translate("MainWindow", "Components"))
        self.lineEdit_ida_components.setText(_translate("MainWindow", "0.80, 0.90"))
        self.lineEdit_nmf_components.setText(_translate("MainWindow", "0.80, 0.90"))
        self.label_nmf_components.setText(_translate("MainWindow", "Components"))
        self.label_nmf_init.setText(_translate("MainWindow", "Init"))
        self.comboBox_nmf_init.setItemText(0, _translate("MainWindow", "random"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage2), _translate("MainWindow", "  Dimension reduction  "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Methods"))
        self.label_filter.setText(_translate("MainWindow", "Filter"))
        self.radioButton_variance_threshold.setText(_translate("MainWindow", "Variance threshold"))
        self.radioButton_correlation.setText(_translate("MainWindow", "Correlation"))
        self.radioButton_distancecorrelation.setText(_translate("MainWindow", "Distance correlation"))
        self.radioButton_fscore.setText(_translate("MainWindow", "F-Score (classification)"))
        self.radioButton_mutualinfo_cls.setText(_translate("MainWindow", "Mutual information (classification)"))
        self.radioButton_mutualinfo_regression.setText(_translate("MainWindow", "Mutual information (regression)"))
        self.radioButton_relieff.setText(_translate("MainWindow", "ReliefF"))
        self.radioButton_anova.setText(_translate("MainWindow", "ANOVA/Ttest2 (classification)"))
        self.label_wrapper.setText(_translate("MainWindow", "Wrapper"))
        self.radioButton_rfe.setText(_translate("MainWindow", "RFE"))
        self.label_embedded.setText(_translate("MainWindow", "Embedded"))
        self.radioButton_l1.setText(_translate("MainWindow", "L1 regularization (Lasso)"))
        self.radioButton_elasticnet.setText(_translate("MainWindow", "L1 + L2 regularization (Elastic net regression)"))
        self.radioButton_featureselection_none.setText(_translate("MainWindow", "None"))
        self.groupBox_feature_selection_setting.setTitle(_translate("MainWindow", "Setting"))
        self.label_variancethreshold_threshold.setText(_translate("MainWindow", "Threshold"))
        self.lineEdit_variancethreshold_threshold.setText(_translate("MainWindow", "0.4, 0.6"))
        self.label_correlation_abscoef.setText(_translate("MainWindow", "Abs_coef"))
        self.lineEdit_correlation_abscoef.setText(_translate("MainWindow", "0.2, 0.4"))
        self.label_distancecorrelation_abscoef.setText(_translate("MainWindow", "Abs_coef"))
        self.lineEdit_distancecorrelation_abscoef.setText(_translate("MainWindow", "0.2, 0.4"))
        self.label_fscore_topnum.setText(_translate("MainWindow", "Top_number"))
        self.lineEdit_fscore_topnum.setText(_translate("MainWindow", "0.4, 0.6"))
        self.label_mutualinfocls_topnum.setText(_translate("MainWindow", "Top_number"))
        self.label_mutualinfo_cls.setText(_translate("MainWindow", "N_neighbors"))
        self.lineEdit_mutualinfocls_topnum.setText(_translate("MainWindow", "0.4, 0.6"))
        self.label_mutualinforeg_topnum.setText(_translate("MainWindow", "N_neighbors"))
        self.label_32.setText(_translate("MainWindow", "Top_number"))
        self.lineEdit_mutualinforeg_topnum.setText(_translate("MainWindow", "0.4, 0.6"))
        self.lineEdit_relieff_topnum.setText(_translate("MainWindow", "np.linspace(0.1,1,5)"))
        self.label_reliffmin.setText(_translate("MainWindow", "Top_numner"))
        self.label_11.setText(_translate("MainWindow", "Multi_correct"))
        self.label_17.setText(_translate("MainWindow", "Top_number"))
        self.lineEdit_anova_topnum.setText(_translate("MainWindow", "0.4, 0.6"))
        self.comboBox_anova_multicorrect.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_anova_multicorrect.setItemText(1, _translate("MainWindow", "FDR"))
        self.comboBox_anova_multicorrect.setItemText(2, _translate("MainWindow", "FWE"))
        self.label_19.setText(_translate("MainWindow", "N_jobs"))
        self.label_16.setText(_translate("MainWindow", "Estimator"))
        self.comboBox_rfe_estimator.setItemText(0, _translate("MainWindow", "SVM"))
        self.comboBox_rfe_estimator.setItemText(1, _translate("MainWindow", "Linear regression"))
        self.comboBox_rfe_estimator.setItemText(2, _translate("MainWindow", "Logistic regression"))
        self.comboBox_rfe_estimator.setItemText(3, _translate("MainWindow", "Ridge regression"))
        self.comboBox_rfe_estimator.setItemText(4, _translate("MainWindow", "Lasso regression"))
        self.comboBox_rfe_estimator.setItemText(5, _translate("MainWindow", "Bayesian ridge regression"))
        self.comboBox_rfe_estimator.setItemText(6, _translate("MainWindow", "Gaussian processes"))
        self.label_15.setText(_translate("MainWindow", "N-fold"))
        self.label_14.setText(_translate("MainWindow", "Step"))
        self.label_40.setText(_translate("MainWindow", "Alpha"))
        self.label_46.setText(_translate("MainWindow", "L1_ratio"))
        self.lineEdit_elasticnet_l1ratio.setText(_translate("MainWindow", "0.5"))
        self.label_44.setText(_translate("MainWindow", "Alpha"))
        self.lineEdit_elasticnet_alpha.setText(_translate("MainWindow", "None"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage3), _translate("MainWindow", "  Feature selection  "))
        self.groupBox_5.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_extractionunder.setText(_translate("MainWindow", "Extraction of majority-minority Tomek links"))
        self.radioButton_smotencover.setText(_translate("MainWindow", "SMOTENC - SMOTE for Nominal Continuous "))
        self.radioButton_nearmissunder.setText(_translate("MainWindow", "NearMiss-(1 and 2 and 3) "))
        self.label_12.setText(_translate("MainWindow", "Over-sampling the minority class"))
        self.radioButton_randunder.setText(_translate("MainWindow", "Random majority under-sampling with replacement"))
        self.radioButton_bsmoteover.setText(_translate("MainWindow", "bSMOTE(1 and 2) - Borderline SMOTE of types 1 and 2"))
        self.radioButton_randover.setText(_translate("MainWindow", "Random minority over-sampling with replacement"))
        self.label_13.setText(_translate("MainWindow", "Under-sampling the majority class(es)"))
        self.radioButton_smoteover.setText(_translate("MainWindow", "SMOTE - Synthetic Minority Over-sampling Technique"))
        self.radioButton_cludterunder.setText(_translate("MainWindow", "Under-sampling with Cluster Centroids"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Setting"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage4), _translate("MainWindow", "  Unbalance treatment  "))
        self.menuConfiguration_file_f.setTitle(_translate("MainWindow", "Configuration file (&F)"))
        self.menuHelp_G.setTitle(_translate("MainWindow", "Help (&H)"))
        self.menuSkin.setTitle(_translate("MainWindow", "Skin"))
        self.actionLoad_configuration.setText(_translate("MainWindow", "Load configuration"))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save configuration"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionDarkOrange.setText(_translate("MainWindow", "DarkOrange"))
        self.actionGray.setText(_translate("MainWindow", "Gray"))
        self.actionBlue.setText(_translate("MainWindow", "Blue"))
        self.actionNavy.setText(_translate("MainWindow", "Navy"))
        self.actionClassic.setText(_translate("MainWindow", "Classic"))
        self.actionGet_all_available_configuraton.setText(_translate("MainWindow", "Get all available configuraton"))

