# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/My_Codes/easylearn-fmri/eslearn/GUI/easylearn_feature_engineering_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 634)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_preprocessing = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preprocessing.sizePolicy().hasHeightForWidth())
        self.pushButton_preprocessing.setSizePolicy(sizePolicy)
        self.pushButton_preprocessing.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_preprocessing.setObjectName("pushButton_preprocessing")
        self.verticalLayout.addWidget(self.pushButton_preprocessing)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_dimreduction = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dimreduction.sizePolicy().hasHeightForWidth())
        self.pushButton_dimreduction.setSizePolicy(sizePolicy)
        self.pushButton_dimreduction.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_dimreduction.setObjectName("pushButton_dimreduction")
        self.verticalLayout.addWidget(self.pushButton_dimreduction)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_selection = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selection.sizePolicy().hasHeightForWidth())
        self.pushButton_selection.setSizePolicy(sizePolicy)
        self.pushButton_selection.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_selection.setObjectName("pushButton_selection")
        self.verticalLayout.addWidget(self.pushButton_selection)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_unbalance_treatment = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_unbalance_treatment.sizePolicy().hasHeightForWidth())
        self.pushButton_unbalance_treatment.setSizePolicy(sizePolicy)
        self.pushButton_unbalance_treatment.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_unbalance_treatment.setObjectName("pushButton_unbalance_treatment")
        self.verticalLayout.addWidget(self.pushButton_unbalance_treatment)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_setting = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_setting.setObjectName("groupBox_setting")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_setting)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget_items = QtWidgets.QStackedWidget(self.groupBox_setting)
        self.stackedWidget_items.setObjectName("stackedWidget_items")
        self.to_preprocessing = QtWidgets.QWidget()
        self.to_preprocessing.setObjectName("to_preprocessing")
        self.gridLayout = QtWidgets.QGridLayout(self.to_preprocessing)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_methods = QtWidgets.QGroupBox(self.to_preprocessing)
        self.groupBox_methods.setObjectName("groupBox_methods")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_methods)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_none_methods = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_none_methods.setObjectName("radioButton_none_methods")
        self.gridLayout_8.addWidget(self.radioButton_none_methods, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 1, 1, 1)
        self.radioButton_demean = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_demean.setObjectName("radioButton_demean")
        self.gridLayout_8.addWidget(self.radioButton_demean, 0, 4, 1, 1)
        self.radioButton_scaling = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_scaling.setObjectName("radioButton_scaling")
        self.gridLayout_8.addWidget(self.radioButton_scaling, 0, 2, 1, 1)
        self.stackedWidget_preprocessing_methods = QtWidgets.QStackedWidget(self.groupBox_methods)
        self.stackedWidget_preprocessing_methods.setObjectName("stackedWidget_preprocessing_methods")
        self.to_zscore = QtWidgets.QWidget()
        self.to_zscore.setObjectName("to_zscore")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.to_zscore)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_9 = QtWidgets.QLabel(self.to_zscore)
        self.label_9.setObjectName("label_9")
        self.gridLayout_17.addWidget(self.label_9, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_zscore)
        self.to_scaling = QtWidgets.QWidget()
        self.to_scaling.setObjectName("to_scaling")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.to_scaling)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_min = QtWidgets.QLabel(self.to_scaling)
        self.label_min.setObjectName("label_min")
        self.gridLayout_10.addWidget(self.label_min, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 0, 4, 1, 1)
        self.label_max = QtWidgets.QLabel(self.to_scaling)
        self.label_max.setObjectName("label_max")
        self.gridLayout_10.addWidget(self.label_max, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 2, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_scaling)
        self.to_demean = QtWidgets.QWidget()
        self.to_demean.setObjectName("to_demean")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.to_demean)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_10 = QtWidgets.QLabel(self.to_demean)
        self.label_10.setObjectName("label_10")
        self.gridLayout_18.addWidget(self.label_10, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_demean)
        self.to_none = QtWidgets.QWidget()
        self.to_none.setObjectName("to_none")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.to_none)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_11 = QtWidgets.QLabel(self.to_none)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_19.addWidget(self.label_11, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_none)
        self.gridLayout_8.addWidget(self.stackedWidget_preprocessing_methods, 1, 0, 1, 7)
        self.radioButton_zscore = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_zscore.setObjectName("radioButton_zscore")
        self.gridLayout_8.addWidget(self.radioButton_zscore, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.groupBox_methods, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem7, 1, 0, 1, 1)
        self.groupBox_level = QtWidgets.QGroupBox(self.to_preprocessing)
        self.groupBox_level.setObjectName("groupBox_level")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_level)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_scaling_subjectlevel = QtWidgets.QRadioButton(self.groupBox_level)
        self.radioButton_scaling_subjectlevel.setObjectName("radioButton_scaling_subjectlevel")
        self.horizontalLayout.addWidget(self.radioButton_scaling_subjectlevel)
        self.radioButton_grouplevel = QtWidgets.QRadioButton(self.groupBox_level)
        self.radioButton_grouplevel.setObjectName("radioButton_grouplevel")
        self.horizontalLayout.addWidget(self.radioButton_grouplevel)
        self.gridLayout.addWidget(self.groupBox_level, 2, 0, 1, 1)
        self.stackedWidget_items.addWidget(self.to_preprocessing)
        self.to_dimreduction = QtWidgets.QWidget()
        self.to_dimreduction.setObjectName("to_dimreduction")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.to_dimreduction)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_pca = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_pca.sizePolicy().hasHeightForWidth())
        self.radioButton_pca.setSizePolicy(sizePolicy)
        self.radioButton_pca.setObjectName("radioButton_pca")
        self.gridLayout_3.addWidget(self.radioButton_pca, 1, 0, 1, 1)
        self.radioButton_ica = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ica.sizePolicy().hasHeightForWidth())
        self.radioButton_ica.setSizePolicy(sizePolicy)
        self.radioButton_ica.setObjectName("radioButton_ica")
        self.gridLayout_3.addWidget(self.radioButton_ica, 1, 2, 1, 1)
        self.radioButton_nmf = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_nmf.sizePolicy().hasHeightForWidth())
        self.radioButton_nmf.setSizePolicy(sizePolicy)
        self.radioButton_nmf.setObjectName("radioButton_nmf")
        self.gridLayout_3.addWidget(self.radioButton_nmf, 1, 4, 1, 1)
        self.stackedWidget_dimreduction = QtWidgets.QStackedWidget(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_dimreduction.sizePolicy().hasHeightForWidth())
        self.stackedWidget_dimreduction.setSizePolicy(sizePolicy)
        self.stackedWidget_dimreduction.setObjectName("stackedWidget_dimreduction")
        self.to_pca = QtWidgets.QWidget()
        self.to_pca.setObjectName("to_pca")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.to_pca)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_n_components = QtWidgets.QLabel(self.to_pca)
        self.label_n_components.setObjectName("label_n_components")
        self.gridLayout_11.addWidget(self.label_n_components, 0, 0, 1, 1)
        self.lineEdit_n_components = QtWidgets.QLineEdit(self.to_pca)
        self.lineEdit_n_components.setObjectName("lineEdit_n_components")
        self.gridLayout_11.addWidget(self.lineEdit_n_components, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_pca)
        self.to_ica = QtWidgets.QWidget()
        self.to_ica.setObjectName("to_ica")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.to_ica)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_n_ic = QtWidgets.QLabel(self.to_ica)
        self.label_n_ic.setObjectName("label_n_ic")
        self.gridLayout_12.addWidget(self.label_n_ic, 0, 0, 1, 1)
        self.lineEdit_n_ic = QtWidgets.QLineEdit(self.to_ica)
        self.lineEdit_n_ic.setObjectName("lineEdit_n_ic")
        self.gridLayout_12.addWidget(self.lineEdit_n_ic, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_ica)
        self.to_lda = QtWidgets.QWidget()
        self.to_lda.setObjectName("to_lda")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.to_lda)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_ida = QtWidgets.QLabel(self.to_lda)
        self.label_ida.setObjectName("label_ida")
        self.gridLayout_13.addWidget(self.label_ida, 0, 0, 1, 1)
        self.lineEdit_ida = QtWidgets.QLineEdit(self.to_lda)
        self.lineEdit_ida.setObjectName("lineEdit_ida")
        self.gridLayout_13.addWidget(self.lineEdit_ida, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_lda)
        self.to_nmf = QtWidgets.QWidget()
        self.to_nmf.setObjectName("to_nmf")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.to_nmf)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_17 = QtWidgets.QLabel(self.to_nmf)
        self.label_17.setObjectName("label_17")
        self.gridLayout_21.addWidget(self.label_17, 0, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.to_nmf)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_21.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.to_nmf)
        self.label_18.setObjectName("label_18")
        self.gridLayout_21.addWidget(self.label_18, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.to_nmf)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_21.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_nmf)
        self.to_None = QtWidgets.QWidget()
        self.to_None.setObjectName("to_None")
        self.label = QtWidgets.QLabel(self.to_None)
        self.label.setGeometry(QtCore.QRect(60, 40, 72, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        self.stackedWidget_dimreduction.addWidget(self.to_None)
        self.gridLayout_3.addWidget(self.stackedWidget_dimreduction, 7, 0, 1, 5)
        self.radioButton_lda = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_lda.sizePolicy().hasHeightForWidth())
        self.radioButton_lda.setSizePolicy(sizePolicy)
        self.radioButton_lda.setObjectName("radioButton_lda")
        self.gridLayout_3.addWidget(self.radioButton_lda, 1, 3, 1, 1)
        self.radioButton_none = QtWidgets.QRadioButton(self.to_dimreduction)
        self.radioButton_none.setObjectName("radioButton_none")
        self.gridLayout_3.addWidget(self.radioButton_none, 1, 5, 1, 1)
        self.stackedWidget_items.addWidget(self.to_dimreduction)
        self.to_selection = QtWidgets.QWidget()
        self.to_selection.setObjectName("to_selection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.to_selection)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_elasticnet = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_elasticnet.setObjectName("radioButton_elasticnet")
        self.gridLayout_4.addWidget(self.radioButton_elasticnet, 20, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.to_selection)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 11, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem8, 12, 0, 1, 1)
        self.radioButton_distancecorrelation = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_distancecorrelation.setObjectName("radioButton_distancecorrelation")
        self.gridLayout_4.addWidget(self.radioButton_distancecorrelation, 4, 0, 1, 1)
        self.radioButton_l2 = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_l2.setObjectName("radioButton_l2")
        self.gridLayout_4.addWidget(self.radioButton_l2, 19, 0, 1, 1)
        self.radioButton_rfe = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_rfe.setObjectName("radioButton_rfe")
        self.gridLayout_4.addWidget(self.radioButton_rfe, 14, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.to_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.radioButton_mutualinfo_regression = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_mutualinfo_regression.setObjectName("radioButton_mutualinfo_regression")
        self.gridLayout_4.addWidget(self.radioButton_mutualinfo_regression, 7, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem10, 16, 0, 1, 1)
        self.radioButton_correlation = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_correlation.setObjectName("radioButton_correlation")
        self.gridLayout_4.addWidget(self.radioButton_correlation, 3, 0, 1, 1)
        self.radioButton_mutualinfo_cls = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_mutualinfo_cls.setObjectName("radioButton_mutualinfo_cls")
        self.gridLayout_4.addWidget(self.radioButton_mutualinfo_cls, 6, 0, 1, 1)
        self.radioButton_l1 = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_l1.setObjectName("radioButton_l1")
        self.gridLayout_4.addWidget(self.radioButton_l1, 18, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.to_selection)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 15, 0, 1, 1)
        self.radioButton_variance_threshold = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_variance_threshold.setObjectName("radioButton_variance_threshold")
        self.gridLayout_4.addWidget(self.radioButton_variance_threshold, 2, 0, 1, 1)
        self.groupBox_feature_selection_input = QtWidgets.QGroupBox(self.to_selection)
        self.groupBox_feature_selection_input.setObjectName("groupBox_feature_selection_input")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_feature_selection_input)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.stackedWidget_feature_selection = QtWidgets.QStackedWidget(self.groupBox_feature_selection_input)
        self.stackedWidget_feature_selection.setObjectName("stackedWidget_feature_selection")
        self.variance_threshold = QtWidgets.QWidget()
        self.variance_threshold.setObjectName("variance_threshold")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.variance_threshold)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_6 = QtWidgets.QLabel(self.variance_threshold)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.variance_threshold)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_15.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.variance_threshold)
        self.correlation = QtWidgets.QWidget()
        self.correlation.setObjectName("correlation")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.correlation)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_7 = QtWidgets.QLabel(self.correlation)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.correlation)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_16.addWidget(self.lineEdit_4, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.correlation)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 1, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.correlation)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_16.addWidget(self.lineEdit_5, 1, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.correlation)
        self.to_distancecorrelation = QtWidgets.QWidget()
        self.to_distancecorrelation.setObjectName("to_distancecorrelation")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.to_distancecorrelation)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_20 = QtWidgets.QLabel(self.to_distancecorrelation)
        self.label_20.setObjectName("label_20")
        self.gridLayout_14.addWidget(self.label_20, 0, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.to_distancecorrelation)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_14.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_distancecorrelation)
        self.to_fscore = QtWidgets.QWidget()
        self.to_fscore.setObjectName("to_fscore")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.to_fscore)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.stackedWidget_feature_selection.addWidget(self.to_fscore)
        self.to_mutualinfo_cls = QtWidgets.QWidget()
        self.to_mutualinfo_cls.setObjectName("to_mutualinfo_cls")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.to_mutualinfo_cls)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_21 = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_21.setObjectName("label_21")
        self.gridLayout_23.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.to_mutualinfo_cls)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_23.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_mutualinfo_cls)
        self.to_mutualinfo_regression = QtWidgets.QWidget()
        self.to_mutualinfo_regression.setObjectName("to_mutualinfo_regression")
        self.stackedWidget_feature_selection.addWidget(self.to_mutualinfo_regression)
        self.to_reliff = QtWidgets.QWidget()
        self.to_reliff.setObjectName("to_reliff")
        self.stackedWidget_feature_selection.addWidget(self.to_reliff)
        self.to_anova = QtWidgets.QWidget()
        self.to_anova.setObjectName("to_anova")
        self.stackedWidget_feature_selection.addWidget(self.to_anova)
        self.to_rfe = QtWidgets.QWidget()
        self.to_rfe.setObjectName("to_rfe")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.to_rfe)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_15 = QtWidgets.QLabel(self.to_rfe)
        self.label_15.setObjectName("label_15")
        self.gridLayout_20.addWidget(self.label_15, 1, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.to_rfe)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_20.addWidget(self.lineEdit_7, 1, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.to_rfe)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_20.addWidget(self.lineEdit_6, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.to_rfe)
        self.label_14.setObjectName("label_14")
        self.gridLayout_20.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.to_rfe)
        self.label_16.setObjectName("label_16")
        self.gridLayout_20.addWidget(self.label_16, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.to_rfe)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_20.addWidget(self.comboBox, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.to_rfe)
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 3, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.to_rfe)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_20.addWidget(self.lineEdit_10, 3, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_rfe)
        self.to_l1 = QtWidgets.QWidget()
        self.to_l1.setObjectName("to_l1")
        self.stackedWidget_feature_selection.addWidget(self.to_l1)
        self.to_l2 = QtWidgets.QWidget()
        self.to_l2.setObjectName("to_l2")
        self.stackedWidget_feature_selection.addWidget(self.to_l2)
        self.to_elasticnet = QtWidgets.QWidget()
        self.to_elasticnet.setObjectName("to_elasticnet")
        self.stackedWidget_feature_selection.addWidget(self.to_elasticnet)
        self.gridLayout_9.addWidget(self.stackedWidget_feature_selection, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_feature_selection_input, 0, 2, 21, 1)
        self.radioButton_anova = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_anova.setObjectName("radioButton_anova")
        self.gridLayout_4.addWidget(self.radioButton_anova, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.to_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 13, 0, 1, 1)
        self.radioButton_relieff = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_relieff.setObjectName("radioButton_relieff")
        self.gridLayout_4.addWidget(self.radioButton_relieff, 8, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.to_selection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 17, 0, 1, 1)
        self.radioButton_fscore = QtWidgets.QRadioButton(self.to_selection)
        self.radioButton_fscore.setObjectName("radioButton_fscore")
        self.gridLayout_4.addWidget(self.radioButton_fscore, 5, 0, 1, 1)
        self.stackedWidget_items.addWidget(self.to_selection)
        self.unbalance_treatment = QtWidgets.QWidget()
        self.unbalance_treatment.setObjectName("unbalance_treatment")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.unbalance_treatment)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.line_3 = QtWidgets.QFrame(self.unbalance_treatment)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 6, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_7.addWidget(self.radioButton_7, 11, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_7.addWidget(self.radioButton_2, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem11, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.unbalance_treatment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 8, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_7.addWidget(self.radioButton_5, 9, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_7.addWidget(self.radioButton_3, 3, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_7.addWidget(self.radioButton_4, 4, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_7.addWidget(self.radioButton_6, 10, 0, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_7.addWidget(self.radioButton_8, 12, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.unbalance_treatment)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.unbalance_treatment)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_7.addWidget(self.radioButton, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem12, 7, 0, 1, 1)
        self.stackedWidget_items.addWidget(self.unbalance_treatment)
        self.to_default_settings = QtWidgets.QWidget()
        self.to_default_settings.setObjectName("to_default_settings")
        self.label_2 = QtWidgets.QLabel(self.to_default_settings)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.stackedWidget_items.addWidget(self.to_default_settings)
        self.gridLayout_5.addWidget(self.stackedWidget_items, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_setting, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_items.setCurrentIndex(2)
        self.stackedWidget_preprocessing_methods.setCurrentIndex(2)
        self.stackedWidget_dimreduction.setCurrentIndex(3)
        self.stackedWidget_feature_selection.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Items"))
        self.pushButton_preprocessing.setText(_translate("MainWindow", "Preprocessing"))
        self.pushButton_dimreduction.setText(_translate("MainWindow", "Dimension reduction"))
        self.pushButton_selection.setText(_translate("MainWindow", "Feature selection"))
        self.pushButton_unbalance_treatment.setText(_translate("MainWindow", "Unbalance treatment"))
        self.groupBox_setting.setTitle(_translate("MainWindow", "Settings"))
        self.groupBox_methods.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_none_methods.setText(_translate("MainWindow", "None"))
        self.radioButton_demean.setText(_translate("MainWindow", "De-mean"))
        self.radioButton_scaling.setText(_translate("MainWindow", "Scaling"))
        self.label_9.setText(_translate("MainWindow", "N/A"))
        self.label_min.setText(_translate("MainWindow", "Min"))
        self.lineEdit_2.setText(_translate("MainWindow", "1"))
        self.label_max.setText(_translate("MainWindow", "Max"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "N/A"))
        self.radioButton_zscore.setText(_translate("MainWindow", "Z-score normalization"))
        self.groupBox_level.setTitle(_translate("MainWindow", "Level"))
        self.radioButton_scaling_subjectlevel.setText(_translate("MainWindow", "Subject"))
        self.radioButton_grouplevel.setText(_translate("MainWindow", "Group"))
        self.radioButton_pca.setText(_translate("MainWindow", "Principal component analysis"))
        self.radioButton_ica.setText(_translate("MainWindow", "Independent component analysis"))
        self.radioButton_nmf.setText(_translate("MainWindow", " Non-negative matrix factorization"))
        self.label_n_components.setText(_translate("MainWindow", "n_components"))
        self.lineEdit_n_components.setText(_translate("MainWindow", "0.95"))
        self.label_n_ic.setText(_translate("MainWindow", "n_ic"))
        self.label_ida.setText(_translate("MainWindow", "N/A"))
        self.label_17.setText(_translate("MainWindow", "N_components"))
        self.label_18.setText(_translate("MainWindow", "Init"))
        self.lineEdit_9.setText(_translate("MainWindow", "random"))
        self.radioButton_lda.setText(_translate("MainWindow", "Latent Dirichlet Allocation"))
        self.radioButton_none.setText(_translate("MainWindow", "None"))
        self.radioButton_elasticnet.setText(_translate("MainWindow", "L1 + L2 regularization (Elastic net regression)"))
        self.radioButton_distancecorrelation.setText(_translate("MainWindow", "Distance correlation"))
        self.radioButton_l2.setText(_translate("MainWindow", "L2 regularization (Ridge regression)"))
        self.radioButton_rfe.setText(_translate("MainWindow", "RFE"))
        self.label_3.setText(_translate("MainWindow", "Filter"))
        self.radioButton_mutualinfo_regression.setText(_translate("MainWindow", "Mutual information (regression)"))
        self.radioButton_correlation.setText(_translate("MainWindow", "Correlation"))
        self.radioButton_mutualinfo_cls.setText(_translate("MainWindow", "Mutual information (classification)"))
        self.radioButton_l1.setText(_translate("MainWindow", "L1 regularization (Lasso)"))
        self.radioButton_variance_threshold.setText(_translate("MainWindow", "Variance threshold"))
        self.groupBox_feature_selection_input.setTitle(_translate("MainWindow", "GroupBox_test"))
        self.label_6.setText(_translate("MainWindow", "Threshold"))
        self.lineEdit_3.setText(_translate("MainWindow", "0.5"))
        self.label_7.setText(_translate("MainWindow", "P value"))
        self.lineEdit_4.setText(_translate("MainWindow", "0.05"))
        self.label_8.setText(_translate("MainWindow", "Absolute coefficient"))
        self.lineEdit_5.setText(_translate("MainWindow", "0.2"))
        self.label_20.setText(_translate("MainWindow", "Absolute coefficient"))
        self.lineEdit_11.setText(_translate("MainWindow", "0.2"))
        self.label_21.setText(_translate("MainWindow", "N_neighbors"))
        self.lineEdit_12.setText(_translate("MainWindow", "3"))
        self.label_15.setText(_translate("MainWindow", "N-fold"))
        self.lineEdit_7.setText(_translate("MainWindow", "5"))
        self.lineEdit_6.setText(_translate("MainWindow", "0.1"))
        self.label_14.setText(_translate("MainWindow", "Step"))
        self.label_16.setText(_translate("MainWindow", "Estimator"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SVM"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Logistic regression"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Gaussian processes"))
        self.label_19.setText(_translate("MainWindow", "N_jobs"))
        self.lineEdit_10.setText(_translate("MainWindow", "-1"))
        self.radioButton_anova.setText(_translate("MainWindow", "ANOVA"))
        self.label_4.setText(_translate("MainWindow", "Wrapper"))
        self.radioButton_relieff.setText(_translate("MainWindow", "ReliefF"))
        self.label_5.setText(_translate("MainWindow", "Embedded"))
        self.radioButton_fscore.setText(_translate("MainWindow", "F-Score"))
        self.radioButton_7.setText(_translate("MainWindow", "Under-sampling with Cluster Centroids"))
        self.radioButton_2.setText(_translate("MainWindow", "SMOTE - Synthetic Minority Over-sampling Technique"))
        self.label_13.setText(_translate("MainWindow", "Under-sampling the majority class(es)"))
        self.radioButton_5.setText(_translate("MainWindow", "Random majority under-sampling with replacement"))
        self.radioButton_3.setText(_translate("MainWindow", "SMOTENC - SMOTE for Nominal Continuous "))
        self.radioButton_4.setText(_translate("MainWindow", "bSMOTE(1 & 2) - Borderline SMOTE of types 1 and 2"))
        self.radioButton_6.setText(_translate("MainWindow", "Extraction of majority-minority Tomek links"))
        self.radioButton_8.setText(_translate("MainWindow", "NearMiss-(1 and 2 and 3) "))
        self.label_12.setText(_translate("MainWindow", "Over-sampling the minority class"))
        self.radioButton.setText(_translate("MainWindow", "Random minority over-sampling with replacement"))

