# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/My_Codes/easylearn-fmri/eslearn/GUI/easylearn_feature_engineering_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_preprocessing = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preprocessing.sizePolicy().hasHeightForWidth())
        self.pushButton_preprocessing.setSizePolicy(sizePolicy)
        self.pushButton_preprocessing.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_preprocessing.setObjectName("pushButton_preprocessing")
        self.verticalLayout.addWidget(self.pushButton_preprocessing)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_dimreduction = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_dimreduction.sizePolicy().hasHeightForWidth())
        self.pushButton_dimreduction.setSizePolicy(sizePolicy)
        self.pushButton_dimreduction.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_dimreduction.setObjectName("pushButton_dimreduction")
        self.verticalLayout.addWidget(self.pushButton_dimreduction)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_selection = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_selection.sizePolicy().hasHeightForWidth())
        self.pushButton_selection.setSizePolicy(sizePolicy)
        self.pushButton_selection.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_selection.setObjectName("pushButton_selection")
        self.verticalLayout.addWidget(self.pushButton_selection)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.pushButton_unbalance_treatment = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_unbalance_treatment.sizePolicy().hasHeightForWidth())
        self.pushButton_unbalance_treatment.setSizePolicy(sizePolicy)
        self.pushButton_unbalance_treatment.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_unbalance_treatment.setObjectName("pushButton_unbalance_treatment")
        self.verticalLayout.addWidget(self.pushButton_unbalance_treatment)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_setting = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_setting.setObjectName("groupBox_setting")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_setting)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget_items = QtWidgets.QStackedWidget(self.groupBox_setting)
        self.stackedWidget_items.setObjectName("stackedWidget_items")
        self.to_preprocessing = QtWidgets.QWidget()
        self.to_preprocessing.setObjectName("to_preprocessing")
        self.gridLayout = QtWidgets.QGridLayout(self.to_preprocessing)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_methods = QtWidgets.QGroupBox(self.to_preprocessing)
        self.groupBox_methods.setObjectName("groupBox_methods")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_methods)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_scaling = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_scaling.setObjectName("radioButton_scaling")
        self.gridLayout_8.addWidget(self.radioButton_scaling, 1, 0, 1, 1)
        self.radioButton_demean = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_demean.setObjectName("radioButton_demean")
        self.gridLayout_8.addWidget(self.radioButton_demean, 2, 0, 1, 1)
        self.radioButton_zscore = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_zscore.setObjectName("radioButton_zscore")
        self.gridLayout_8.addWidget(self.radioButton_zscore, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods = QtWidgets.QStackedWidget(self.groupBox_methods)
        self.stackedWidget_preprocessing_methods.setObjectName("stackedWidget_preprocessing_methods")
        self.to_scaling = QtWidgets.QWidget()
        self.to_scaling.setObjectName("to_scaling")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.to_scaling)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_min = QtWidgets.QLabel(self.to_scaling)
        self.label_min.setObjectName("label_min")
        self.gridLayout_10.addWidget(self.label_min, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_max = QtWidgets.QLabel(self.to_scaling)
        self.label_max.setObjectName("label_max")
        self.gridLayout_10.addWidget(self.label_max, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_scaling)
        self.to_default = QtWidgets.QWidget()
        self.to_default.setObjectName("to_default")
        self.stackedWidget_preprocessing_methods.addWidget(self.to_default)
        self.gridLayout_8.addWidget(self.stackedWidget_preprocessing_methods, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_methods, 0, 0, 1, 1)
        self.groupBox_level = QtWidgets.QGroupBox(self.to_preprocessing)
        self.groupBox_level.setObjectName("groupBox_level")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_level)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.radioButton_grouplevel = QtWidgets.QRadioButton(self.groupBox_level)
        self.radioButton_grouplevel.setObjectName("radioButton_grouplevel")
        self.gridLayout_9.addWidget(self.radioButton_grouplevel, 0, 0, 1, 1)
        self.radioButton_scaling_subjectlevel = QtWidgets.QRadioButton(self.groupBox_level)
        self.radioButton_scaling_subjectlevel.setObjectName("radioButton_scaling_subjectlevel")
        self.gridLayout_9.addWidget(self.radioButton_scaling_subjectlevel, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_level, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.stackedWidget_items.addWidget(self.to_preprocessing)
        self.to_dimreduction = QtWidgets.QWidget()
        self.to_dimreduction.setObjectName("to_dimreduction")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.to_dimreduction)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_lle = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_lle.sizePolicy().hasHeightForWidth())
        self.radioButton_lle.setSizePolicy(sizePolicy)
        self.radioButton_lle.setObjectName("radioButton_lle")
        self.gridLayout_3.addWidget(self.radioButton_lle, 1, 3, 1, 1)
        self.radioButton_ica = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ica.sizePolicy().hasHeightForWidth())
        self.radioButton_ica.setSizePolicy(sizePolicy)
        self.radioButton_ica.setObjectName("radioButton_ica")
        self.gridLayout_3.addWidget(self.radioButton_ica, 1, 1, 1, 1)
        self.radioButton_pca = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_pca.sizePolicy().hasHeightForWidth())
        self.radioButton_pca.setSizePolicy(sizePolicy)
        self.radioButton_pca.setObjectName("radioButton_pca")
        self.gridLayout_3.addWidget(self.radioButton_pca, 1, 0, 1, 1)
        self.radioButton_lda = QtWidgets.QRadioButton(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_lda.sizePolicy().hasHeightForWidth())
        self.radioButton_lda.setSizePolicy(sizePolicy)
        self.radioButton_lda.setObjectName("radioButton_lda")
        self.gridLayout_3.addWidget(self.radioButton_lda, 1, 2, 1, 1)
        self.stackedWidget_dimreduction = QtWidgets.QStackedWidget(self.to_dimreduction)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_dimreduction.sizePolicy().hasHeightForWidth())
        self.stackedWidget_dimreduction.setSizePolicy(sizePolicy)
        self.stackedWidget_dimreduction.setObjectName("stackedWidget_dimreduction")
        self.to_pca = QtWidgets.QWidget()
        self.to_pca.setObjectName("to_pca")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.to_pca)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label = QtWidgets.QLabel(self.to_pca)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.to_pca)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_11.addWidget(self.lineEdit_3, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_pca)
        self.to_ica = QtWidgets.QWidget()
        self.to_ica.setObjectName("to_ica")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.to_ica)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_3 = QtWidgets.QLabel(self.to_ica)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.to_ica)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_12.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_ica)
        self.to_lda = QtWidgets.QWidget()
        self.to_lda.setObjectName("to_lda")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.to_lda)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_4 = QtWidgets.QLabel(self.to_lda)
        self.label_4.setObjectName("label_4")
        self.gridLayout_13.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.to_lda)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_13.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_lda)
        self.to_lle = QtWidgets.QWidget()
        self.to_lle.setObjectName("to_lle")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.to_lle)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_5 = QtWidgets.QLabel(self.to_lle)
        self.label_5.setObjectName("label_5")
        self.gridLayout_14.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.to_lle)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_14.addWidget(self.lineEdit_6, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_lle)
        self.gridLayout_3.addWidget(self.stackedWidget_dimreduction, 7, 0, 1, 4)
        self.stackedWidget_items.addWidget(self.to_dimreduction)
        self.to_default_setting = QtWidgets.QWidget()
        self.to_default_setting.setObjectName("to_default_setting")
        self.stackedWidget_items.addWidget(self.to_default_setting)
        self.to_selection = QtWidgets.QWidget()
        self.to_selection.setObjectName("to_selection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.to_selection)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_embedded = QtWidgets.QGroupBox(self.to_selection)
        self.groupBox_embedded.setObjectName("groupBox_embedded")
        self.gridLayout_4.addWidget(self.groupBox_embedded, 4, 0, 1, 1)
        self.groupBox_filter = QtWidgets.QGroupBox(self.to_selection)
        self.groupBox_filter.setObjectName("groupBox_filter")
        self.gridLayout_4.addWidget(self.groupBox_filter, 0, 0, 1, 1)
        self.groupBox_wrapper = QtWidgets.QGroupBox(self.to_selection)
        self.groupBox_wrapper.setObjectName("groupBox_wrapper")
        self.gridLayout_4.addWidget(self.groupBox_wrapper, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem6, 3, 0, 1, 1)
        self.stackedWidget_items.addWidget(self.to_selection)
        self.to_dealing_with_unbalance = QtWidgets.QWidget()
        self.to_dealing_with_unbalance.setObjectName("to_dealing_with_unbalance")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.to_dealing_with_unbalance)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.to_dealing_with_unbalance)
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.gridLayout_7.addWidget(self.textBrowser_7, 0, 0, 1, 1)
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.to_dealing_with_unbalance)
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.gridLayout_7.addWidget(self.textBrowser_8, 0, 1, 1, 1)
        self.stackedWidget_items.addWidget(self.to_dealing_with_unbalance)
        self.to_default_settings = QtWidgets.QWidget()
        self.to_default_settings.setObjectName("to_default_settings")
        self.label_2 = QtWidgets.QLabel(self.to_default_settings)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 72, 15))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.stackedWidget_items.addWidget(self.to_default_settings)
        self.gridLayout_5.addWidget(self.stackedWidget_items, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_setting, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget_items.setCurrentIndex(3)
        self.stackedWidget_preprocessing_methods.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Items"))
        self.pushButton_preprocessing.setText(_translate("MainWindow", "Preprocessing"))
        self.pushButton_dimreduction.setText(_translate("MainWindow", "Dimension reduction"))
        self.pushButton_selection.setText(_translate("MainWindow", "Feature selection"))
        self.pushButton_unbalance_treatment.setText(_translate("MainWindow", "Unbalance treatment"))
        self.groupBox_setting.setTitle(_translate("MainWindow", "Settings"))
        self.groupBox_methods.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_scaling.setText(_translate("MainWindow", "Scaling"))
        self.radioButton_demean.setText(_translate("MainWindow", "De-mean"))
        self.radioButton_zscore.setText(_translate("MainWindow", "Z-score normalization"))
        self.label_min.setText(_translate("MainWindow", "Min"))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.label_max.setText(_translate("MainWindow", "Max"))
        self.lineEdit_2.setText(_translate("MainWindow", "1"))
        self.groupBox_level.setTitle(_translate("MainWindow", "Level"))
        self.radioButton_grouplevel.setText(_translate("MainWindow", "Group"))
        self.radioButton_scaling_subjectlevel.setText(_translate("MainWindow", "Subject"))
        self.radioButton_lle.setText(_translate("MainWindow", "LLE"))
        self.radioButton_ica.setText(_translate("MainWindow", "ICA"))
        self.radioButton_pca.setText(_translate("MainWindow", "PCA"))
        self.radioButton_lda.setText(_translate("MainWindow", "LDA"))
        self.label.setText(_translate("MainWindow", "n_components"))
        self.lineEdit_3.setText(_translate("MainWindow", "0.95"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_embedded.setTitle(_translate("MainWindow", "Embedded"))
        self.groupBox_filter.setTitle(_translate("MainWindow", "Filter"))
        self.groupBox_wrapper.setTitle(_translate("MainWindow", "Wrapper"))
        self.textBrowser_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dealing with unbalance</p></body></html>"))

