# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/My_Codes/easylearn-fmri/eslearn/GUI/easylearn_feature_engineering_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 727)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.tabWidget_items = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_items.sizePolicy().hasHeightForWidth())
        self.tabWidget_items.setSizePolicy(sizePolicy)
        self.tabWidget_items.setMinimumSize(QtCore.QSize(100, 100))
        self.tabWidget_items.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_items.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_items.setObjectName("tabWidget_items")
        self.tabWidget_itemsPage1 = QtWidgets.QWidget()
        self.tabWidget_itemsPage1.setObjectName("tabWidget_itemsPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.tabWidget_itemsPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_preprocessing_setting = QtWidgets.QGroupBox(self.tabWidget_itemsPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_preprocessing_setting.sizePolicy().hasHeightForWidth())
        self.groupBox_preprocessing_setting.setSizePolicy(sizePolicy)
        self.groupBox_preprocessing_setting.setMinimumSize(QtCore.QSize(300, 80))
        self.groupBox_preprocessing_setting.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.groupBox_preprocessing_setting.setObjectName("groupBox_preprocessing_setting")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_preprocessing_setting)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.stackedWidget_preprocessing_methods = QtWidgets.QStackedWidget(self.groupBox_preprocessing_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_preprocessing_methods.sizePolicy().hasHeightForWidth())
        self.stackedWidget_preprocessing_methods.setSizePolicy(sizePolicy)
        self.stackedWidget_preprocessing_methods.setObjectName("stackedWidget_preprocessing_methods")
        self.to_zscore = QtWidgets.QWidget()
        self.to_zscore.setObjectName("to_zscore")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.to_zscore)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_zscore = QtWidgets.QLabel(self.to_zscore)
        self.label_zscore.setText("")
        self.label_zscore.setObjectName("label_zscore")
        self.gridLayout_17.addWidget(self.label_zscore, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_zscore)
        self.to_scaling = QtWidgets.QWidget()
        self.to_scaling.setObjectName("to_scaling")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.to_scaling)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_scaling_max = QtWidgets.QLabel(self.to_scaling)
        self.label_scaling_max.setObjectName("label_scaling_max")
        self.gridLayout_10.addWidget(self.label_scaling_max, 0, 0, 1, 1)
        self.lineEdit_scaling_min = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit_scaling_min.setObjectName("lineEdit_scaling_min")
        self.gridLayout_10.addWidget(self.lineEdit_scaling_min, 1, 1, 1, 1)
        self.label_scaling_min = QtWidgets.QLabel(self.to_scaling)
        self.label_scaling_min.setObjectName("label_scaling_min")
        self.gridLayout_10.addWidget(self.label_scaling_min, 1, 0, 1, 1)
        self.lineEdit_scaling_max = QtWidgets.QLineEdit(self.to_scaling)
        self.lineEdit_scaling_max.setObjectName("lineEdit_scaling_max")
        self.gridLayout_10.addWidget(self.lineEdit_scaling_max, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem, 0, 2, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_scaling)
        self.to_demean = QtWidgets.QWidget()
        self.to_demean.setObjectName("to_demean")
        self.stackedWidget_preprocessing_methods.addWidget(self.to_demean)
        self.to_none = QtWidgets.QWidget()
        self.to_none.setObjectName("to_none")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.to_none)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_none = QtWidgets.QLabel(self.to_none)
        self.label_none.setText("")
        self.label_none.setObjectName("label_none")
        self.gridLayout_19.addWidget(self.label_none, 0, 0, 1, 1)
        self.stackedWidget_preprocessing_methods.addWidget(self.to_none)
        self.gridLayout_26.addWidget(self.stackedWidget_preprocessing_methods, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_preprocessing_setting, 0, 2, 1, 1)
        self.groupBox_methods = QtWidgets.QGroupBox(self.tabWidget_itemsPage1)
        self.groupBox_methods.setObjectName("groupBox_methods")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_methods)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.radioButton_none_methods = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_none_methods.setObjectName("radioButton_none_methods")
        self.gridLayout_8.addWidget(self.radioButton_none_methods, 3, 0, 1, 1)
        self.radioButton_demean = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_demean.setObjectName("radioButton_demean")
        self.gridLayout_8.addWidget(self.radioButton_demean, 2, 0, 1, 1)
        self.radioButton_zscore = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_zscore.setObjectName("radioButton_zscore")
        self.gridLayout_8.addWidget(self.radioButton_zscore, 0, 0, 1, 1)
        self.radioButton_scaling = QtWidgets.QRadioButton(self.groupBox_methods)
        self.radioButton_scaling.setObjectName("radioButton_scaling")
        self.gridLayout_8.addWidget(self.radioButton_scaling, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_methods, 0, 0, 1, 1)
        self.groupBox_level = QtWidgets.QGroupBox(self.tabWidget_itemsPage1)
        self.groupBox_level.setObjectName("groupBox_level")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_level)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_grouplevel = QtWidgets.QRadioButton(self.groupBox_level)
        self.radioButton_grouplevel.setObjectName("radioButton_grouplevel")
        self.verticalLayout.addWidget(self.radioButton_grouplevel)
        self.radioButton_subjectlevel = QtWidgets.QRadioButton(self.groupBox_level)
        self.radioButton_subjectlevel.setObjectName("radioButton_subjectlevel")
        self.verticalLayout.addWidget(self.radioButton_subjectlevel)
        self.gridLayout.addWidget(self.groupBox_level, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage1, "")
        self.tabWidget_itemsPage2 = QtWidgets.QWidget()
        self.tabWidget_itemsPage2.setObjectName("tabWidget_itemsPage2")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.tabWidget_itemsPage2)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.groupBox = QtWidgets.QGroupBox(self.tabWidget_itemsPage2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.radioButton_lda = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_lda.sizePolicy().hasHeightForWidth())
        self.radioButton_lda.setSizePolicy(sizePolicy)
        self.radioButton_lda.setObjectName("radioButton_lda")
        self.gridLayout_28.addWidget(self.radioButton_lda, 3, 0, 1, 1)
        self.radioButton_ica = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_ica.sizePolicy().hasHeightForWidth())
        self.radioButton_ica.setSizePolicy(sizePolicy)
        self.radioButton_ica.setObjectName("radioButton_ica")
        self.gridLayout_28.addWidget(self.radioButton_ica, 1, 0, 1, 1)
        self.radioButton_nmf = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_nmf.sizePolicy().hasHeightForWidth())
        self.radioButton_nmf.setSizePolicy(sizePolicy)
        self.radioButton_nmf.setObjectName("radioButton_nmf")
        self.gridLayout_28.addWidget(self.radioButton_nmf, 2, 0, 1, 1)
        self.radioButton_pca = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_pca.sizePolicy().hasHeightForWidth())
        self.radioButton_pca.setSizePolicy(sizePolicy)
        self.radioButton_pca.setObjectName("radioButton_pca")
        self.gridLayout_28.addWidget(self.radioButton_pca, 0, 0, 1, 1)
        self.radioButton_none = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_none.setObjectName("radioButton_none")
        self.gridLayout_28.addWidget(self.radioButton_none, 4, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox, 0, 0, 2, 1)
        self.label = QtWidgets.QLabel(self.tabWidget_itemsPage2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_29.addWidget(self.label, 0, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabWidget_itemsPage2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget_dimreduction = QtWidgets.QStackedWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_dimreduction.sizePolicy().hasHeightForWidth())
        self.stackedWidget_dimreduction.setSizePolicy(sizePolicy)
        self.stackedWidget_dimreduction.setObjectName("stackedWidget_dimreduction")
        self.to_pca = QtWidgets.QWidget()
        self.to_pca.setObjectName("to_pca")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.to_pca)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_n_components = QtWidgets.QLabel(self.to_pca)
        self.label_n_components.setObjectName("label_n_components")
        self.gridLayout_11.addWidget(self.label_n_components, 0, 0, 1, 1)
        self.doubleSpinBox_pca_maxcomponents = QtWidgets.QDoubleSpinBox(self.to_pca)
        self.doubleSpinBox_pca_maxcomponents.setMaximum(1.0)
        self.doubleSpinBox_pca_maxcomponents.setSingleStep(0.1)
        self.doubleSpinBox_pca_maxcomponents.setProperty("value", 0.99)
        self.doubleSpinBox_pca_maxcomponents.setObjectName("doubleSpinBox_pca_maxcomponents")
        self.gridLayout_11.addWidget(self.doubleSpinBox_pca_maxcomponents, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.to_pca)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBox_pca_mincomponents = QtWidgets.QDoubleSpinBox(self.to_pca)
        self.doubleSpinBox_pca_mincomponents.setMaximum(1.0)
        self.doubleSpinBox_pca_mincomponents.setSingleStep(0.1)
        self.doubleSpinBox_pca_mincomponents.setProperty("value", 0.01)
        self.doubleSpinBox_pca_mincomponents.setObjectName("doubleSpinBox_pca_mincomponents")
        self.gridLayout_11.addWidget(self.doubleSpinBox_pca_mincomponents, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.to_pca)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 2, 0, 1, 1)
        self.spinBox_pcanum = QtWidgets.QSpinBox(self.to_pca)
        self.spinBox_pcanum.setMaximum(10000)
        self.spinBox_pcanum.setSingleStep(5)
        self.spinBox_pcanum.setProperty("value", 10)
        self.spinBox_pcanum.setObjectName("spinBox_pcanum")
        self.gridLayout_11.addWidget(self.spinBox_pcanum, 2, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_pca)
        self.to_ica = QtWidgets.QWidget()
        self.to_ica.setObjectName("to_ica")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.to_ica)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_n_ic = QtWidgets.QLabel(self.to_ica)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_n_ic.sizePolicy().hasHeightForWidth())
        self.label_n_ic.setSizePolicy(sizePolicy)
        self.label_n_ic.setObjectName("label_n_ic")
        self.gridLayout_6.addWidget(self.label_n_ic, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.to_ica)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 2, 0, 1, 1)
        self.spinBox_icnum = QtWidgets.QSpinBox(self.to_ica)
        self.spinBox_icnum.setMaximum(10000)
        self.spinBox_icnum.setSingleStep(5)
        self.spinBox_icnum.setProperty("value", 10)
        self.spinBox_icnum.setObjectName("spinBox_icnum")
        self.gridLayout_6.addWidget(self.spinBox_icnum, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.to_ica)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 2, 1, 1)
        self.doubleSpinBox_ica_maxics = QtWidgets.QDoubleSpinBox(self.to_ica)
        self.doubleSpinBox_ica_maxics.setMaximum(1.0)
        self.doubleSpinBox_ica_maxics.setSingleStep(0.1)
        self.doubleSpinBox_ica_maxics.setProperty("value", 0.99)
        self.doubleSpinBox_ica_maxics.setObjectName("doubleSpinBox_ica_maxics")
        self.gridLayout_6.addWidget(self.doubleSpinBox_ica_maxics, 0, 1, 1, 1)
        self.doubleSpinBox_ica_minics = QtWidgets.QDoubleSpinBox(self.to_ica)
        self.doubleSpinBox_ica_minics.setMaximum(1.0)
        self.doubleSpinBox_ica_minics.setSingleStep(0.1)
        self.doubleSpinBox_ica_minics.setProperty("value", 0.01)
        self.doubleSpinBox_ica_minics.setObjectName("doubleSpinBox_ica_minics")
        self.gridLayout_6.addWidget(self.doubleSpinBox_ica_minics, 1, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_ica)
        self.to_lda = QtWidgets.QWidget()
        self.to_lda.setObjectName("to_lda")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.to_lda)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_ida = QtWidgets.QLabel(self.to_lda)
        self.label_ida.setObjectName("label_ida")
        self.gridLayout_13.addWidget(self.label_ida, 0, 0, 1, 1)
        self.lineEdit_ida = QtWidgets.QLineEdit(self.to_lda)
        self.lineEdit_ida.setObjectName("lineEdit_ida")
        self.gridLayout_13.addWidget(self.lineEdit_ida, 0, 1, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_lda)
        self.to_nmf = QtWidgets.QWidget()
        self.to_nmf.setObjectName("to_nmf")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.to_nmf)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_label_nmf_mincompnents = QtWidgets.QLabel(self.to_nmf)
        self.label_label_nmf_mincompnents.setObjectName("label_label_nmf_mincompnents")
        self.gridLayout_21.addWidget(self.label_label_nmf_mincompnents, 1, 0, 1, 2)
        self.spinBox_nmfnum = QtWidgets.QSpinBox(self.to_nmf)
        self.spinBox_nmfnum.setMaximum(10000)
        self.spinBox_nmfnum.setSingleStep(5)
        self.spinBox_nmfnum.setProperty("value", 10)
        self.spinBox_nmfnum.setObjectName("spinBox_nmfnum")
        self.gridLayout_21.addWidget(self.spinBox_nmfnum, 3, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_nmf_maxcompnents = QtWidgets.QLabel(self.to_nmf)
        self.label_nmf_maxcompnents.setObjectName("label_nmf_maxcompnents")
        self.gridLayout_21.addWidget(self.label_nmf_maxcompnents, 0, 0, 1, 2)
        self.label_38 = QtWidgets.QLabel(self.to_nmf)
        self.label_38.setObjectName("label_38")
        self.gridLayout_21.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_nmf_init = QtWidgets.QLabel(self.to_nmf)
        self.label_nmf_init.setObjectName("label_nmf_init")
        self.gridLayout_21.addWidget(self.label_nmf_init, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.to_nmf)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_21.addWidget(self.comboBox_2, 4, 2, 1, 1)
        self.doubleSpinBox_nmf_maxcomponents = QtWidgets.QDoubleSpinBox(self.to_nmf)
        self.doubleSpinBox_nmf_maxcomponents.setMaximum(1.0)
        self.doubleSpinBox_nmf_maxcomponents.setSingleStep(0.1)
        self.doubleSpinBox_nmf_maxcomponents.setProperty("value", 1.0)
        self.doubleSpinBox_nmf_maxcomponents.setObjectName("doubleSpinBox_nmf_maxcomponents")
        self.gridLayout_21.addWidget(self.doubleSpinBox_nmf_maxcomponents, 0, 2, 1, 1)
        self.doubleSpinBox_nmf_mincompnents = QtWidgets.QDoubleSpinBox(self.to_nmf)
        self.doubleSpinBox_nmf_mincompnents.setMaximum(1.0)
        self.doubleSpinBox_nmf_mincompnents.setSingleStep(0.1)
        self.doubleSpinBox_nmf_mincompnents.setProperty("value", 0.01)
        self.doubleSpinBox_nmf_mincompnents.setObjectName("doubleSpinBox_nmf_mincompnents")
        self.gridLayout_21.addWidget(self.doubleSpinBox_nmf_mincompnents, 1, 2, 1, 1)
        self.stackedWidget_dimreduction.addWidget(self.to_nmf)
        self.to_none_dimreduction = QtWidgets.QWidget()
        self.to_none_dimreduction.setObjectName("to_none_dimreduction")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.to_none_dimreduction)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.stackedWidget_dimreduction.addWidget(self.to_none_dimreduction)
        self.gridLayout_3.addWidget(self.stackedWidget_dimreduction, 0, 0, 1, 1)
        self.gridLayout_29.addWidget(self.groupBox_2, 0, 1, 2, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage2, "")
        self.tabWidget_itemsPage3 = QtWidgets.QWidget()
        self.tabWidget_itemsPage3.setObjectName("tabWidget_itemsPage3")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.tabWidget_itemsPage3)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabWidget_itemsPage3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_filter = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filter.sizePolicy().hasHeightForWidth())
        self.label_filter.setSizePolicy(sizePolicy)
        self.label_filter.setObjectName("label_filter")
        self.gridLayout_4.addWidget(self.label_filter, 0, 0, 1, 1)
        self.radioButton_variance_threshold = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_variance_threshold.setObjectName("radioButton_variance_threshold")
        self.gridLayout_4.addWidget(self.radioButton_variance_threshold, 1, 0, 1, 1)
        self.radioButton_correlation = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_correlation.setObjectName("radioButton_correlation")
        self.gridLayout_4.addWidget(self.radioButton_correlation, 2, 0, 1, 1)
        self.radioButton_distancecorrelation = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_distancecorrelation.setObjectName("radioButton_distancecorrelation")
        self.gridLayout_4.addWidget(self.radioButton_distancecorrelation, 3, 0, 1, 1)
        self.radioButton_fscore = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_fscore.setObjectName("radioButton_fscore")
        self.gridLayout_4.addWidget(self.radioButton_fscore, 4, 0, 1, 1)
        self.radioButton_mutualinfo_cls = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_mutualinfo_cls.setObjectName("radioButton_mutualinfo_cls")
        self.gridLayout_4.addWidget(self.radioButton_mutualinfo_cls, 5, 0, 1, 1)
        self.radioButton_mutualinfo_regression = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_mutualinfo_regression.setObjectName("radioButton_mutualinfo_regression")
        self.gridLayout_4.addWidget(self.radioButton_mutualinfo_regression, 6, 0, 1, 1)
        self.radioButton_relieff = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_relieff.setObjectName("radioButton_relieff")
        self.gridLayout_4.addWidget(self.radioButton_relieff, 7, 0, 1, 1)
        self.radioButton_anova = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_anova.setObjectName("radioButton_anova")
        self.gridLayout_4.addWidget(self.radioButton_anova, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 9, 0, 1, 1)
        self.label_wrapper = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_wrapper.sizePolicy().hasHeightForWidth())
        self.label_wrapper.setSizePolicy(sizePolicy)
        self.label_wrapper.setObjectName("label_wrapper")
        self.gridLayout_4.addWidget(self.label_wrapper, 10, 0, 1, 1)
        self.radioButton_rfe = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_rfe.setObjectName("radioButton_rfe")
        self.gridLayout_4.addWidget(self.radioButton_rfe, 11, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 12, 0, 1, 1)
        self.label_embedded = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_embedded.sizePolicy().hasHeightForWidth())
        self.label_embedded.setSizePolicy(sizePolicy)
        self.label_embedded.setObjectName("label_embedded")
        self.gridLayout_4.addWidget(self.label_embedded, 13, 0, 1, 1)
        self.radioButton_l1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_l1.setObjectName("radioButton_l1")
        self.gridLayout_4.addWidget(self.radioButton_l1, 14, 0, 1, 1)
        self.radioButton_elasticnet = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_elasticnet.setObjectName("radioButton_elasticnet")
        self.gridLayout_4.addWidget(self.radioButton_elasticnet, 15, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 16, 0, 1, 1)
        self.radioButton_featureselection_none = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_featureselection_none.setObjectName("radioButton_featureselection_none")
        self.gridLayout_4.addWidget(self.radioButton_featureselection_none, 17, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 18, 0, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_3, 0, 0, 2, 2)
        self.groupBox_feature_selection_input = QtWidgets.QGroupBox(self.tabWidget_itemsPage3)
        self.groupBox_feature_selection_input.setObjectName("groupBox_feature_selection_input")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_feature_selection_input)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.stackedWidget_feature_selection = QtWidgets.QStackedWidget(self.groupBox_feature_selection_input)
        self.stackedWidget_feature_selection.setObjectName("stackedWidget_feature_selection")
        self.to_variance_threshold = QtWidgets.QWidget()
        self.to_variance_threshold.setObjectName("to_variance_threshold")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.to_variance_threshold)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_variancesthreshold = QtWidgets.QLabel(self.to_variance_threshold)
        self.label_variancesthreshold.setObjectName("label_variancesthreshold")
        self.gridLayout_15.addWidget(self.label_variancesthreshold, 0, 0, 1, 1)
        self.doubleSpinBox_variancethreshold_min = QtWidgets.QDoubleSpinBox(self.to_variance_threshold)
        self.doubleSpinBox_variancethreshold_min.setMaximum(1.0)
        self.doubleSpinBox_variancethreshold_min.setSingleStep(0.1)
        self.doubleSpinBox_variancethreshold_min.setProperty("value", 0.1)
        self.doubleSpinBox_variancethreshold_min.setObjectName("doubleSpinBox_variancethreshold_min")
        self.gridLayout_15.addWidget(self.doubleSpinBox_variancethreshold_min, 1, 1, 1, 1)
        self.doubleSpinBox_variancethreshold_max = QtWidgets.QDoubleSpinBox(self.to_variance_threshold)
        self.doubleSpinBox_variancethreshold_max.setMaximum(1.0)
        self.doubleSpinBox_variancethreshold_max.setSingleStep(0.1)
        self.doubleSpinBox_variancethreshold_max.setProperty("value", 0.8)
        self.doubleSpinBox_variancethreshold_max.setObjectName("doubleSpinBox_variancethreshold_max")
        self.gridLayout_15.addWidget(self.doubleSpinBox_variancethreshold_max, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.to_variance_threshold)
        self.label_18.setObjectName("label_18")
        self.gridLayout_15.addWidget(self.label_18, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.to_variance_threshold)
        self.label_20.setObjectName("label_20")
        self.gridLayout_15.addWidget(self.label_20, 2, 0, 1, 1)
        self.spinBox_variancethreshold_num = QtWidgets.QSpinBox(self.to_variance_threshold)
        self.spinBox_variancethreshold_num.setMaximum(10000)
        self.spinBox_variancethreshold_num.setSingleStep(5)
        self.spinBox_variancethreshold_num.setProperty("value", 10)
        self.spinBox_variancethreshold_num.setObjectName("spinBox_variancethreshold_num")
        self.gridLayout_15.addWidget(self.spinBox_variancethreshold_num, 2, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_variance_threshold)
        self.correlation = QtWidgets.QWidget()
        self.correlation.setObjectName("correlation")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.correlation)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.doubleSpinBox_correlation_minabscoef = QtWidgets.QDoubleSpinBox(self.correlation)
        self.doubleSpinBox_correlation_minabscoef.setMaximum(1.0)
        self.doubleSpinBox_correlation_minabscoef.setSingleStep(0.1)
        self.doubleSpinBox_correlation_minabscoef.setProperty("value", 0.01)
        self.doubleSpinBox_correlation_minabscoef.setObjectName("doubleSpinBox_correlation_minabscoef")
        self.gridLayout_16.addWidget(self.doubleSpinBox_correlation_minabscoef, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.correlation)
        self.label_7.setObjectName("label_7")
        self.gridLayout_16.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.correlation)
        self.label_21.setObjectName("label_21")
        self.gridLayout_16.addWidget(self.label_21, 2, 0, 1, 1)
        self.doubleSpinBox_correlation_maxabscoef = QtWidgets.QDoubleSpinBox(self.correlation)
        self.doubleSpinBox_correlation_maxabscoef.setMaximum(1.0)
        self.doubleSpinBox_correlation_maxabscoef.setSingleStep(0.1)
        self.doubleSpinBox_correlation_maxabscoef.setProperty("value", 1.0)
        self.doubleSpinBox_correlation_maxabscoef.setObjectName("doubleSpinBox_correlation_maxabscoef")
        self.gridLayout_16.addWidget(self.doubleSpinBox_correlation_maxabscoef, 0, 2, 1, 1)
        self.spinBox_correlation_num = QtWidgets.QSpinBox(self.correlation)
        self.spinBox_correlation_num.setMaximum(10000)
        self.spinBox_correlation_num.setSingleStep(5)
        self.spinBox_correlation_num.setProperty("value", 10)
        self.spinBox_correlation_num.setObjectName("spinBox_correlation_num")
        self.gridLayout_16.addWidget(self.spinBox_correlation_num, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.correlation)
        self.label_8.setObjectName("label_8")
        self.gridLayout_16.addWidget(self.label_8, 1, 0, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.correlation)
        self.to_distancecorrelation = QtWidgets.QWidget()
        self.to_distancecorrelation.setObjectName("to_distancecorrelation")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.to_distancecorrelation)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_22 = QtWidgets.QLabel(self.to_distancecorrelation)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 0, 1, 1)
        self.spinBox_distancecorrelation_num = QtWidgets.QSpinBox(self.to_distancecorrelation)
        self.spinBox_distancecorrelation_num.setMaximum(10000)
        self.spinBox_distancecorrelation_num.setSingleStep(5)
        self.spinBox_distancecorrelation_num.setProperty("value", 10)
        self.spinBox_distancecorrelation_num.setObjectName("spinBox_distancecorrelation_num")
        self.gridLayout_2.addWidget(self.spinBox_distancecorrelation_num, 2, 1, 1, 1)
        self.doubleSpinBox_distancecorrelation_maxabscoef = QtWidgets.QDoubleSpinBox(self.to_distancecorrelation)
        self.doubleSpinBox_distancecorrelation_maxabscoef.setMaximum(1.0)
        self.doubleSpinBox_distancecorrelation_maxabscoef.setSingleStep(0.1)
        self.doubleSpinBox_distancecorrelation_maxabscoef.setProperty("value", 1.0)
        self.doubleSpinBox_distancecorrelation_maxabscoef.setObjectName("doubleSpinBox_distancecorrelation_maxabscoef")
        self.gridLayout_2.addWidget(self.doubleSpinBox_distancecorrelation_maxabscoef, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.to_distancecorrelation)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 1)
        self.doubleSpinBox_distancecorrelation_minabscoef = QtWidgets.QDoubleSpinBox(self.to_distancecorrelation)
        self.doubleSpinBox_distancecorrelation_minabscoef.setMaximum(1.0)
        self.doubleSpinBox_distancecorrelation_minabscoef.setSingleStep(0.1)
        self.doubleSpinBox_distancecorrelation_minabscoef.setProperty("value", 0.0)
        self.doubleSpinBox_distancecorrelation_minabscoef.setObjectName("doubleSpinBox_distancecorrelation_minabscoef")
        self.gridLayout_2.addWidget(self.doubleSpinBox_distancecorrelation_minabscoef, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.to_distancecorrelation)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_distancecorrelation)
        self.to_fscore = QtWidgets.QWidget()
        self.to_fscore.setObjectName("to_fscore")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.to_fscore)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.doubleSpinBox_fscore_minnum = QtWidgets.QDoubleSpinBox(self.to_fscore)
        self.doubleSpinBox_fscore_minnum.setMaximum(1.0)
        self.doubleSpinBox_fscore_minnum.setSingleStep(0.1)
        self.doubleSpinBox_fscore_minnum.setProperty("value", 0.01)
        self.doubleSpinBox_fscore_minnum.setObjectName("doubleSpinBox_fscore_minnum")
        self.gridLayout_14.addWidget(self.doubleSpinBox_fscore_minnum, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.to_fscore)
        self.label_27.setObjectName("label_27")
        self.gridLayout_14.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.to_fscore)
        self.label_26.setObjectName("label_26")
        self.gridLayout_14.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.to_fscore)
        self.label_25.setObjectName("label_25")
        self.gridLayout_14.addWidget(self.label_25, 2, 0, 1, 1)
        self.spinBox_fscore_num = QtWidgets.QSpinBox(self.to_fscore)
        self.spinBox_fscore_num.setMaximum(10000)
        self.spinBox_fscore_num.setSingleStep(5)
        self.spinBox_fscore_num.setProperty("value", 10)
        self.spinBox_fscore_num.setObjectName("spinBox_fscore_num")
        self.gridLayout_14.addWidget(self.spinBox_fscore_num, 2, 1, 1, 1)
        self.doubleSpinBox_fscore_maxnum = QtWidgets.QDoubleSpinBox(self.to_fscore)
        self.doubleSpinBox_fscore_maxnum.setMaximum(1.0)
        self.doubleSpinBox_fscore_maxnum.setSingleStep(0.1)
        self.doubleSpinBox_fscore_maxnum.setProperty("value", 1.0)
        self.doubleSpinBox_fscore_maxnum.setObjectName("doubleSpinBox_fscore_maxnum")
        self.gridLayout_14.addWidget(self.doubleSpinBox_fscore_maxnum, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem7, 0, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_fscore)
        self.to_mutualinfo_cls = QtWidgets.QWidget()
        self.to_mutualinfo_cls.setObjectName("to_mutualinfo_cls")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.to_mutualinfo_cls)
        self.gridLayout_22.setObjectName("gridLayout_22")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem8, 4, 2, 1, 1)
        self.label_mutualinfo_cls = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_mutualinfo_cls.setObjectName("label_mutualinfo_cls")
        self.gridLayout_22.addWidget(self.label_mutualinfo_cls, 5, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_28.setObjectName("label_28")
        self.gridLayout_22.addWidget(self.label_28, 4, 0, 1, 1)
        self.spinBox_mutualinfocls_num = QtWidgets.QSpinBox(self.to_mutualinfo_cls)
        self.spinBox_mutualinfocls_num.setMaximum(10000)
        self.spinBox_mutualinfocls_num.setSingleStep(5)
        self.spinBox_mutualinfocls_num.setProperty("value", 10)
        self.spinBox_mutualinfocls_num.setObjectName("spinBox_mutualinfocls_num")
        self.gridLayout_22.addWidget(self.spinBox_mutualinfocls_num, 4, 1, 1, 1)
        self.doubleSpinBox_mutualinfocls_maxnum = QtWidgets.QDoubleSpinBox(self.to_mutualinfo_cls)
        self.doubleSpinBox_mutualinfocls_maxnum.setMaximum(1.0)
        self.doubleSpinBox_mutualinfocls_maxnum.setSingleStep(0.1)
        self.doubleSpinBox_mutualinfocls_maxnum.setProperty("value", 1.0)
        self.doubleSpinBox_mutualinfocls_maxnum.setObjectName("doubleSpinBox_mutualinfocls_maxnum")
        self.gridLayout_22.addWidget(self.doubleSpinBox_mutualinfocls_maxnum, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_30.setObjectName("label_30")
        self.gridLayout_22.addWidget(self.label_30, 2, 0, 1, 1)
        self.spinBox_mutualinfocls_neighbors = QtWidgets.QSpinBox(self.to_mutualinfo_cls)
        self.spinBox_mutualinfocls_neighbors.setProperty("value", 3)
        self.spinBox_mutualinfocls_neighbors.setObjectName("spinBox_mutualinfocls_neighbors")
        self.gridLayout_22.addWidget(self.spinBox_mutualinfocls_neighbors, 5, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.to_mutualinfo_cls)
        self.label_29.setObjectName("label_29")
        self.gridLayout_22.addWidget(self.label_29, 3, 0, 1, 1)
        self.doubleSpinBox_mutualinfocls_minnum = QtWidgets.QDoubleSpinBox(self.to_mutualinfo_cls)
        self.doubleSpinBox_mutualinfocls_minnum.setMaximum(1.0)
        self.doubleSpinBox_mutualinfocls_minnum.setSingleStep(0.1)
        self.doubleSpinBox_mutualinfocls_minnum.setProperty("value", 0.0)
        self.doubleSpinBox_mutualinfocls_minnum.setObjectName("doubleSpinBox_mutualinfocls_minnum")
        self.gridLayout_22.addWidget(self.doubleSpinBox_mutualinfocls_minnum, 3, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_mutualinfo_cls)
        self.to_mutualinfo_regression = QtWidgets.QWidget()
        self.to_mutualinfo_regression.setObjectName("to_mutualinfo_regression")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.to_mutualinfo_regression)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.doubleSpinBox_mutualinforeg_minnum = QtWidgets.QDoubleSpinBox(self.to_mutualinfo_regression)
        self.doubleSpinBox_mutualinforeg_minnum.setMaximum(1.0)
        self.doubleSpinBox_mutualinforeg_minnum.setSingleStep(0.1)
        self.doubleSpinBox_mutualinforeg_minnum.setProperty("value", 0.0)
        self.doubleSpinBox_mutualinforeg_minnum.setObjectName("doubleSpinBox_mutualinforeg_minnum")
        self.gridLayout_12.addWidget(self.doubleSpinBox_mutualinforeg_minnum, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.to_mutualinfo_regression)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 1, 0, 1, 1)
        self.label_mutualinforeg = QtWidgets.QLabel(self.to_mutualinfo_regression)
        self.label_mutualinforeg.setObjectName("label_mutualinforeg")
        self.gridLayout_12.addWidget(self.label_mutualinforeg, 3, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.to_mutualinfo_regression)
        self.label_31.setObjectName("label_31")
        self.gridLayout_12.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.to_mutualinfo_regression)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 2, 0, 1, 1)
        self.spinBox_mutualinforeg_num = QtWidgets.QSpinBox(self.to_mutualinfo_regression)
        self.spinBox_mutualinforeg_num.setMaximum(10000)
        self.spinBox_mutualinforeg_num.setSingleStep(5)
        self.spinBox_mutualinforeg_num.setProperty("value", 10)
        self.spinBox_mutualinforeg_num.setObjectName("spinBox_mutualinforeg_num")
        self.gridLayout_12.addWidget(self.spinBox_mutualinforeg_num, 2, 1, 1, 1)
        self.doubleSpinBox_mutualinforeg_maxnum = QtWidgets.QDoubleSpinBox(self.to_mutualinfo_regression)
        self.doubleSpinBox_mutualinforeg_maxnum.setMaximum(1.0)
        self.doubleSpinBox_mutualinforeg_maxnum.setSingleStep(0.1)
        self.doubleSpinBox_mutualinforeg_maxnum.setProperty("value", 1.0)
        self.doubleSpinBox_mutualinforeg_maxnum.setObjectName("doubleSpinBox_mutualinforeg_maxnum")
        self.gridLayout_12.addWidget(self.doubleSpinBox_mutualinforeg_maxnum, 0, 1, 1, 1)
        self.spinBox_mutualinforeg_neighbors = QtWidgets.QSpinBox(self.to_mutualinfo_regression)
        self.spinBox_mutualinforeg_neighbors.setProperty("value", 3)
        self.spinBox_mutualinforeg_neighbors.setObjectName("spinBox_mutualinforeg_neighbors")
        self.gridLayout_12.addWidget(self.spinBox_mutualinforeg_neighbors, 3, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem9, 0, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_mutualinfo_regression)
        self.to_reliff = QtWidgets.QWidget()
        self.to_reliff.setObjectName("to_reliff")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.to_reliff)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_relieffmax = QtWidgets.QLabel(self.to_reliff)
        self.label_relieffmax.setObjectName("label_relieffmax")
        self.gridLayout_18.addWidget(self.label_relieffmax, 0, 0, 1, 1)
        self.doubleSpinBox_relieff_max = QtWidgets.QDoubleSpinBox(self.to_reliff)
        self.doubleSpinBox_relieff_max.setMaximum(1.0)
        self.doubleSpinBox_relieff_max.setSingleStep(0.1)
        self.doubleSpinBox_relieff_max.setProperty("value", 1.0)
        self.doubleSpinBox_relieff_max.setObjectName("doubleSpinBox_relieff_max")
        self.gridLayout_18.addWidget(self.doubleSpinBox_relieff_max, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 0, 2, 1, 1)
        self.label_reliffmin = QtWidgets.QLabel(self.to_reliff)
        self.label_reliffmin.setObjectName("label_reliffmin")
        self.gridLayout_18.addWidget(self.label_reliffmin, 1, 0, 1, 1)
        self.doubleSpinBox_relieff_min = QtWidgets.QDoubleSpinBox(self.to_reliff)
        self.doubleSpinBox_relieff_min.setMaximum(1.0)
        self.doubleSpinBox_relieff_min.setSingleStep(0.1)
        self.doubleSpinBox_relieff_min.setObjectName("doubleSpinBox_relieff_min")
        self.gridLayout_18.addWidget(self.doubleSpinBox_relieff_min, 1, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.to_reliff)
        self.label_34.setObjectName("label_34")
        self.gridLayout_18.addWidget(self.label_34, 2, 0, 1, 1)
        self.spinBox_relief_num = QtWidgets.QSpinBox(self.to_reliff)
        self.spinBox_relief_num.setMaximum(10000)
        self.spinBox_relief_num.setSingleStep(5)
        self.spinBox_relief_num.setProperty("value", 10)
        self.spinBox_relief_num.setObjectName("spinBox_relief_num")
        self.gridLayout_18.addWidget(self.spinBox_relief_num, 2, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_reliff)
        self.to_anova = QtWidgets.QWidget()
        self.to_anova.setObjectName("to_anova")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.to_anova)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_10 = QtWidgets.QLabel(self.to_anova)
        self.label_10.setObjectName("label_10")
        self.gridLayout_23.addWidget(self.label_10, 0, 0, 1, 1)
        self.doubleSpinBox_anova_alpha_max = QtWidgets.QDoubleSpinBox(self.to_anova)
        self.doubleSpinBox_anova_alpha_max.setMaximum(1.0)
        self.doubleSpinBox_anova_alpha_max.setSingleStep(0.01)
        self.doubleSpinBox_anova_alpha_max.setProperty("value", 1.0)
        self.doubleSpinBox_anova_alpha_max.setObjectName("doubleSpinBox_anova_alpha_max")
        self.gridLayout_23.addWidget(self.doubleSpinBox_anova_alpha_max, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.to_anova)
        self.label_17.setObjectName("label_17")
        self.gridLayout_23.addWidget(self.label_17, 1, 0, 1, 1)
        self.doubleSpinBox_anova_alpha_min = QtWidgets.QDoubleSpinBox(self.to_anova)
        self.doubleSpinBox_anova_alpha_min.setMaximum(1.0)
        self.doubleSpinBox_anova_alpha_min.setSingleStep(0.01)
        self.doubleSpinBox_anova_alpha_min.setProperty("value", 0.0)
        self.doubleSpinBox_anova_alpha_min.setObjectName("doubleSpinBox_anova_alpha_min")
        self.gridLayout_23.addWidget(self.doubleSpinBox_anova_alpha_min, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.to_anova)
        self.label_11.setObjectName("label_11")
        self.gridLayout_23.addWidget(self.label_11, 2, 0, 1, 1)
        self.comboBox_anova_multicorrect = QtWidgets.QComboBox(self.to_anova)
        self.comboBox_anova_multicorrect.setObjectName("comboBox_anova_multicorrect")
        self.comboBox_anova_multicorrect.addItem("")
        self.comboBox_anova_multicorrect.addItem("")
        self.comboBox_anova_multicorrect.addItem("")
        self.gridLayout_23.addWidget(self.comboBox_anova_multicorrect, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.to_anova)
        self.label_35.setObjectName("label_35")
        self.gridLayout_23.addWidget(self.label_35, 3, 0, 1, 1)
        self.spinBox_anova_num = QtWidgets.QSpinBox(self.to_anova)
        self.spinBox_anova_num.setMaximum(10000)
        self.spinBox_anova_num.setSingleStep(5)
        self.spinBox_anova_num.setProperty("value", 10)
        self.spinBox_anova_num.setObjectName("spinBox_anova_num")
        self.gridLayout_23.addWidget(self.spinBox_anova_num, 3, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_anova)
        self.to_rfe = QtWidgets.QWidget()
        self.to_rfe.setObjectName("to_rfe")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.to_rfe)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_15 = QtWidgets.QLabel(self.to_rfe)
        self.label_15.setObjectName("label_15")
        self.gridLayout_20.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.to_rfe)
        self.label_14.setObjectName("label_14")
        self.gridLayout_20.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.to_rfe)
        self.label_16.setObjectName("label_16")
        self.gridLayout_20.addWidget(self.label_16, 2, 0, 1, 1)
        self.comboBox_rfe_estimator = QtWidgets.QComboBox(self.to_rfe)
        self.comboBox_rfe_estimator.setObjectName("comboBox_rfe_estimator")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.comboBox_rfe_estimator.addItem("")
        self.gridLayout_20.addWidget(self.comboBox_rfe_estimator, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.to_rfe)
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 3, 0, 1, 1)
        self.spinBox_rfe_nfold = QtWidgets.QSpinBox(self.to_rfe)
        self.spinBox_rfe_nfold.setMinimum(2)
        self.spinBox_rfe_nfold.setMaximum(1000)
        self.spinBox_rfe_nfold.setProperty("value", 5)
        self.spinBox_rfe_nfold.setObjectName("spinBox_rfe_nfold")
        self.gridLayout_20.addWidget(self.spinBox_rfe_nfold, 1, 2, 1, 1)
        self.doubleSpinBox_rfe_step = QtWidgets.QDoubleSpinBox(self.to_rfe)
        self.doubleSpinBox_rfe_step.setMaximum(10000.0)
        self.doubleSpinBox_rfe_step.setSingleStep(0.1)
        self.doubleSpinBox_rfe_step.setProperty("value", 0.1)
        self.doubleSpinBox_rfe_step.setObjectName("doubleSpinBox_rfe_step")
        self.gridLayout_20.addWidget(self.doubleSpinBox_rfe_step, 0, 2, 1, 1)
        self.spinBox_rfe_njobs = QtWidgets.QSpinBox(self.to_rfe)
        self.spinBox_rfe_njobs.setMinimum(-1)
        self.spinBox_rfe_njobs.setProperty("value", -1)
        self.spinBox_rfe_njobs.setObjectName("spinBox_rfe_njobs")
        self.gridLayout_20.addWidget(self.spinBox_rfe_njobs, 3, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_rfe)
        self.to_l1 = QtWidgets.QWidget()
        self.to_l1.setObjectName("to_l1")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.to_l1)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_39 = QtWidgets.QLabel(self.to_l1)
        self.label_39.setObjectName("label_39")
        self.gridLayout_24.addWidget(self.label_39, 0, 0, 1, 1)
        self.doubleSpinBox_l1_alpha_min = QtWidgets.QDoubleSpinBox(self.to_l1)
        self.doubleSpinBox_l1_alpha_min.setMaximum(100000.0)
        self.doubleSpinBox_l1_alpha_min.setSingleStep(100.0)
        self.doubleSpinBox_l1_alpha_min.setProperty("value", 0.0)
        self.doubleSpinBox_l1_alpha_min.setObjectName("doubleSpinBox_l1_alpha_min")
        self.gridLayout_24.addWidget(self.doubleSpinBox_l1_alpha_min, 1, 1, 1, 1)
        self.spinBox_l1_num = QtWidgets.QSpinBox(self.to_l1)
        self.spinBox_l1_num.setMaximum(10000)
        self.spinBox_l1_num.setSingleStep(5)
        self.spinBox_l1_num.setProperty("value", 10)
        self.spinBox_l1_num.setObjectName("spinBox_l1_num")
        self.gridLayout_24.addWidget(self.spinBox_l1_num, 2, 1, 1, 1)
        self.doubleSpinBox_l1_alpha_max = QtWidgets.QDoubleSpinBox(self.to_l1)
        self.doubleSpinBox_l1_alpha_max.setMaximum(100000.0)
        self.doubleSpinBox_l1_alpha_max.setSingleStep(100.0)
        self.doubleSpinBox_l1_alpha_max.setProperty("value", 100.0)
        self.doubleSpinBox_l1_alpha_max.setObjectName("doubleSpinBox_l1_alpha_max")
        self.gridLayout_24.addWidget(self.doubleSpinBox_l1_alpha_max, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.to_l1)
        self.label_40.setObjectName("label_40")
        self.gridLayout_24.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.to_l1)
        self.label_41.setObjectName("label_41")
        self.gridLayout_24.addWidget(self.label_41, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem11, 0, 2, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_l1)
        self.to_elasticnet = QtWidgets.QWidget()
        self.to_elasticnet.setObjectName("to_elasticnet")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.to_elasticnet)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_43 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_43.setObjectName("label_43")
        self.gridLayout_25.addWidget(self.label_43, 0, 0, 1, 1)
        self.doubleSpinBox_elasticnet_alpha_max = QtWidgets.QDoubleSpinBox(self.to_elasticnet)
        self.doubleSpinBox_elasticnet_alpha_max.setMaximum(100000.0)
        self.doubleSpinBox_elasticnet_alpha_max.setSingleStep(100.0)
        self.doubleSpinBox_elasticnet_alpha_max.setProperty("value", 100.0)
        self.doubleSpinBox_elasticnet_alpha_max.setObjectName("doubleSpinBox_elasticnet_alpha_max")
        self.gridLayout_25.addWidget(self.doubleSpinBox_elasticnet_alpha_max, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem12, 0, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_44.setObjectName("label_44")
        self.gridLayout_25.addWidget(self.label_44, 1, 0, 1, 1)
        self.doubleSpinBox_elasticnet_alpha_min = QtWidgets.QDoubleSpinBox(self.to_elasticnet)
        self.doubleSpinBox_elasticnet_alpha_min.setMaximum(100000.0)
        self.doubleSpinBox_elasticnet_alpha_min.setSingleStep(100.0)
        self.doubleSpinBox_elasticnet_alpha_min.setProperty("value", 0.0)
        self.doubleSpinBox_elasticnet_alpha_min.setObjectName("doubleSpinBox_elasticnet_alpha_min")
        self.gridLayout_25.addWidget(self.doubleSpinBox_elasticnet_alpha_min, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_42.setObjectName("label_42")
        self.gridLayout_25.addWidget(self.label_42, 2, 0, 1, 1)
        self.spinBox_elasticnet_num = QtWidgets.QSpinBox(self.to_elasticnet)
        self.spinBox_elasticnet_num.setMaximum(10000)
        self.spinBox_elasticnet_num.setSingleStep(5)
        self.spinBox_elasticnet_num.setProperty("value", 10)
        self.spinBox_elasticnet_num.setObjectName("spinBox_elasticnet_num")
        self.gridLayout_25.addWidget(self.spinBox_elasticnet_num, 2, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_45.setObjectName("label_45")
        self.gridLayout_25.addWidget(self.label_45, 3, 0, 1, 1)
        self.doubleSpinBox_elasticnet_l1ratio_max = QtWidgets.QDoubleSpinBox(self.to_elasticnet)
        self.doubleSpinBox_elasticnet_l1ratio_max.setMaximum(1.0)
        self.doubleSpinBox_elasticnet_l1ratio_max.setSingleStep(0.1)
        self.doubleSpinBox_elasticnet_l1ratio_max.setProperty("value", 1.0)
        self.doubleSpinBox_elasticnet_l1ratio_max.setObjectName("doubleSpinBox_elasticnet_l1ratio_max")
        self.gridLayout_25.addWidget(self.doubleSpinBox_elasticnet_l1ratio_max, 3, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_46.setObjectName("label_46")
        self.gridLayout_25.addWidget(self.label_46, 4, 0, 1, 1)
        self.doubleSpinBox_elasticnet_l1ratio_min = QtWidgets.QDoubleSpinBox(self.to_elasticnet)
        self.doubleSpinBox_elasticnet_l1ratio_min.setMaximum(1.0)
        self.doubleSpinBox_elasticnet_l1ratio_min.setSingleStep(0.1)
        self.doubleSpinBox_elasticnet_l1ratio_min.setProperty("value", 0.0)
        self.doubleSpinBox_elasticnet_l1ratio_min.setObjectName("doubleSpinBox_elasticnet_l1ratio_min")
        self.gridLayout_25.addWidget(self.doubleSpinBox_elasticnet_l1ratio_min, 4, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.to_elasticnet)
        self.label_47.setObjectName("label_47")
        self.gridLayout_25.addWidget(self.label_47, 5, 0, 1, 1)
        self.spinBox_l1ratio_num = QtWidgets.QSpinBox(self.to_elasticnet)
        self.spinBox_l1ratio_num.setMaximum(10000)
        self.spinBox_l1ratio_num.setSingleStep(5)
        self.spinBox_l1ratio_num.setProperty("value", 10)
        self.spinBox_l1ratio_num.setObjectName("spinBox_l1ratio_num")
        self.gridLayout_25.addWidget(self.spinBox_l1ratio_num, 5, 1, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_elasticnet)
        self.to_none_featureselection = QtWidgets.QWidget()
        self.to_none_featureselection.setObjectName("to_none_featureselection")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.to_none_featureselection)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.label_none_featureselection = QtWidgets.QLabel(self.to_none_featureselection)
        self.label_none_featureselection.setText("")
        self.label_none_featureselection.setObjectName("label_none_featureselection")
        self.gridLayout_27.addWidget(self.label_none_featureselection, 0, 0, 1, 1)
        self.stackedWidget_feature_selection.addWidget(self.to_none_featureselection)
        self.gridLayout_9.addWidget(self.stackedWidget_feature_selection, 0, 1, 1, 1)
        self.gridLayout_30.addWidget(self.groupBox_feature_selection_input, 0, 2, 2, 1)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_30.addItem(spacerItem13, 1, 1, 1, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage3, "")
        self.tabWidget_itemsPage4 = QtWidgets.QWidget()
        self.tabWidget_itemsPage4.setObjectName("tabWidget_itemsPage4")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.tabWidget_itemsPage4)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabWidget_itemsPage4)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButton_extractionunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_extractionunder.setObjectName("radioButton_extractionunder")
        self.gridLayout_7.addWidget(self.radioButton_extractionunder, 8, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 5, 0, 1, 1)
        self.radioButton_smotencover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_smotencover.setObjectName("radioButton_smotencover")
        self.gridLayout_7.addWidget(self.radioButton_smotencover, 3, 0, 1, 1)
        self.radioButton_nearmissunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_nearmissunder.setObjectName("radioButton_nearmissunder")
        self.gridLayout_7.addWidget(self.radioButton_nearmissunder, 10, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
        self.radioButton_randunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_randunder.setObjectName("radioButton_randunder")
        self.gridLayout_7.addWidget(self.radioButton_randunder, 7, 0, 1, 1)
        self.radioButton_bsmoteover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_bsmoteover.setObjectName("radioButton_bsmoteover")
        self.gridLayout_7.addWidget(self.radioButton_bsmoteover, 4, 0, 1, 1)
        self.radioButton_randover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_randover.setCheckable(True)
        self.radioButton_randover.setChecked(False)
        self.radioButton_randover.setObjectName("radioButton_randover")
        self.gridLayout_7.addWidget(self.radioButton_randover, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 6, 0, 1, 1)
        self.radioButton_smoteover = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_smoteover.setObjectName("radioButton_smoteover")
        self.gridLayout_7.addWidget(self.radioButton_smoteover, 2, 0, 1, 1)
        self.radioButton_cludterunder = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_cludterunder.setObjectName("radioButton_cludterunder")
        self.gridLayout_7.addWidget(self.radioButton_cludterunder, 9, 0, 1, 1)
        self.gridLayout_31.addWidget(self.groupBox_5, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_31.addItem(spacerItem14, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabWidget_itemsPage4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_31.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.tabWidget_items.addTab(self.tabWidget_itemsPage4, "")
        self.gridLayout_32.addWidget(self.tabWidget_items, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 26))
        self.menubar.setObjectName("menubar")
        self.menuConfiguration_file_f = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration_file_f.setObjectName("menuConfiguration_file_f")
        self.menuHelp_G = QtWidgets.QMenu(self.menubar)
        self.menuHelp_G.setObjectName("menuHelp_G")
        self.menuSkin = QtWidgets.QMenu(self.menubar)
        self.menuSkin.setObjectName("menuSkin")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_configuration = QtWidgets.QAction(MainWindow)
        self.actionLoad_configuration.setObjectName("actionLoad_configuration")
        self.actionSave_configuration = QtWidgets.QAction(MainWindow)
        self.actionSave_configuration.setObjectName("actionSave_configuration")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionDarkOrange = QtWidgets.QAction(MainWindow)
        self.actionDarkOrange.setObjectName("actionDarkOrange")
        self.actionGray = QtWidgets.QAction(MainWindow)
        self.actionGray.setObjectName("actionGray")
        self.actionBlue = QtWidgets.QAction(MainWindow)
        self.actionBlue.setObjectName("actionBlue")
        self.actionNavy = QtWidgets.QAction(MainWindow)
        self.actionNavy.setObjectName("actionNavy")
        self.actionClassic = QtWidgets.QAction(MainWindow)
        self.actionClassic.setObjectName("actionClassic")
        self.actionGet_all_available_configuraton = QtWidgets.QAction(MainWindow)
        self.actionGet_all_available_configuraton.setObjectName("actionGet_all_available_configuraton")
        self.menuConfiguration_file_f.addAction(self.actionLoad_configuration)
        self.menuConfiguration_file_f.addAction(self.actionSave_configuration)
        self.menuConfiguration_file_f.addAction(self.actionGet_all_available_configuraton)
        self.menuSkin.addAction(self.actionDark)
        self.menuSkin.addAction(self.actionBlack)
        self.menuSkin.addAction(self.actionDarkOrange)
        self.menuSkin.addAction(self.actionGray)
        self.menuSkin.addAction(self.actionBlue)
        self.menuSkin.addAction(self.actionNavy)
        self.menuSkin.addAction(self.actionClassic)
        self.menubar.addAction(self.menuConfiguration_file_f.menuAction())
        self.menubar.addAction(self.menuHelp_G.menuAction())
        self.menubar.addAction(self.menuSkin.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_items.setCurrentIndex(2)
        self.stackedWidget_preprocessing_methods.setCurrentIndex(3)
        self.stackedWidget_dimreduction.setCurrentIndex(4)
        self.stackedWidget_feature_selection.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_preprocessing_setting.setTitle(_translate("MainWindow", "Setting"))
        self.label_scaling_max.setText(_translate("MainWindow", "Max"))
        self.lineEdit_scaling_min.setText(_translate("MainWindow", "0"))
        self.label_scaling_min.setText(_translate("MainWindow", "Min"))
        self.lineEdit_scaling_max.setText(_translate("MainWindow", "1"))
        self.groupBox_methods.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_none_methods.setText(_translate("MainWindow", "None"))
        self.radioButton_demean.setText(_translate("MainWindow", "De-mean"))
        self.radioButton_zscore.setText(_translate("MainWindow", "Z-score normalization"))
        self.radioButton_scaling.setText(_translate("MainWindow", "Scaling"))
        self.groupBox_level.setTitle(_translate("MainWindow", "Level"))
        self.radioButton_grouplevel.setText(_translate("MainWindow", "Group"))
        self.radioButton_subjectlevel.setText(_translate("MainWindow", "Subject"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage1), _translate("MainWindow", "  Preprocessing  "))
        self.groupBox.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_lda.setText(_translate("MainWindow", "Latent Dirichlet Allocation"))
        self.radioButton_ica.setText(_translate("MainWindow", "Independent component analysis"))
        self.radioButton_nmf.setText(_translate("MainWindow", "Non-negative matrix factorization"))
        self.radioButton_pca.setText(_translate("MainWindow", "Principal component analysis"))
        self.radioButton_none.setText(_translate("MainWindow", "None"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Setting"))
        self.label_n_components.setText(_translate("MainWindow", "Max_components"))
        self.label_2.setText(_translate("MainWindow", "Min_components"))
        self.label_36.setText(_translate("MainWindow", "Number"))
        self.label_n_ic.setText(_translate("MainWindow", "Max_ics"))
        self.label_37.setText(_translate("MainWindow", "Number"))
        self.label_9.setText(_translate("MainWindow", "Min_ics"))
        self.label_ida.setText(_translate("MainWindow", "N/A"))
        self.label_label_nmf_mincompnents.setText(_translate("MainWindow", "Min_components"))
        self.label_nmf_maxcompnents.setText(_translate("MainWindow", "Max_components"))
        self.label_38.setText(_translate("MainWindow", "Number"))
        self.label_nmf_init.setText(_translate("MainWindow", "Init"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "random"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage2), _translate("MainWindow", "  Dimension reduction  "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Methods"))
        self.label_filter.setText(_translate("MainWindow", "Filter"))
        self.radioButton_variance_threshold.setText(_translate("MainWindow", "Variance threshold"))
        self.radioButton_correlation.setText(_translate("MainWindow", "Correlation"))
        self.radioButton_distancecorrelation.setText(_translate("MainWindow", "Distance correlation"))
        self.radioButton_fscore.setText(_translate("MainWindow", "F-Score (classification)"))
        self.radioButton_mutualinfo_cls.setText(_translate("MainWindow", "Mutual information (classification)"))
        self.radioButton_mutualinfo_regression.setText(_translate("MainWindow", "Mutual information (regression)"))
        self.radioButton_relieff.setText(_translate("MainWindow", "ReliefF"))
        self.radioButton_anova.setText(_translate("MainWindow", "ANOVA/Ttest2 (classification)"))
        self.label_wrapper.setText(_translate("MainWindow", "Wrapper"))
        self.radioButton_rfe.setText(_translate("MainWindow", "RFE"))
        self.label_embedded.setText(_translate("MainWindow", "Embedded"))
        self.radioButton_l1.setText(_translate("MainWindow", "L1 regularization (Lasso)"))
        self.radioButton_elasticnet.setText(_translate("MainWindow", "L1 + L2 regularization (Elastic net regression)"))
        self.radioButton_featureselection_none.setText(_translate("MainWindow", "None"))
        self.groupBox_feature_selection_input.setTitle(_translate("MainWindow", "Setting"))
        self.label_variancesthreshold.setText(_translate("MainWindow", "Max_threshold"))
        self.label_18.setText(_translate("MainWindow", "Min_threshold"))
        self.label_20.setText(_translate("MainWindow", "Number"))
        self.label_7.setText(_translate("MainWindow", "Max_abs_coef"))
        self.label_21.setText(_translate("MainWindow", "Number"))
        self.label_8.setText(_translate("MainWindow", "Min_abs_coef"))
        self.label_22.setText(_translate("MainWindow", "Number"))
        self.label_23.setText(_translate("MainWindow", "Max_abs_coef"))
        self.label_24.setText(_translate("MainWindow", "Min_abs_coef"))
        self.label_27.setText(_translate("MainWindow", "Min_num"))
        self.label_26.setText(_translate("MainWindow", "Max_num"))
        self.label_25.setText(_translate("MainWindow", "Number"))
        self.label_mutualinfo_cls.setText(_translate("MainWindow", "N_neighbors"))
        self.label_28.setText(_translate("MainWindow", "Number"))
        self.label_30.setText(_translate("MainWindow", "Max_num"))
        self.label_29.setText(_translate("MainWindow", "Min_num"))
        self.label_32.setText(_translate("MainWindow", "Min_num"))
        self.label_mutualinforeg.setText(_translate("MainWindow", "N_neighbors"))
        self.label_31.setText(_translate("MainWindow", "Max_num"))
        self.label_33.setText(_translate("MainWindow", "Number"))
        self.label_relieffmax.setText(_translate("MainWindow", "Max_features"))
        self.label_reliffmin.setText(_translate("MainWindow", "Min_feature"))
        self.label_34.setText(_translate("MainWindow", "Number"))
        self.label_10.setText(_translate("MainWindow", "Max_number"))
        self.label_17.setText(_translate("MainWindow", "Min_number"))
        self.label_11.setText(_translate("MainWindow", "Multi_correct"))
        self.comboBox_anova_multicorrect.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_anova_multicorrect.setItemText(1, _translate("MainWindow", "FDR"))
        self.comboBox_anova_multicorrect.setItemText(2, _translate("MainWindow", "FWE"))
        self.label_35.setText(_translate("MainWindow", "Number"))
        self.label_15.setText(_translate("MainWindow", "N-fold"))
        self.label_14.setText(_translate("MainWindow", "Step"))
        self.label_16.setText(_translate("MainWindow", "Estimator"))
        self.comboBox_rfe_estimator.setItemText(0, _translate("MainWindow", "SVM"))
        self.comboBox_rfe_estimator.setItemText(1, _translate("MainWindow", "Linear regression"))
        self.comboBox_rfe_estimator.setItemText(2, _translate("MainWindow", "Logistic regression"))
        self.comboBox_rfe_estimator.setItemText(3, _translate("MainWindow", "Ridge regression"))
        self.comboBox_rfe_estimator.setItemText(4, _translate("MainWindow", "Lasso regression"))
        self.comboBox_rfe_estimator.setItemText(5, _translate("MainWindow", "Bayesian ridge regression"))
        self.comboBox_rfe_estimator.setItemText(6, _translate("MainWindow", "Gaussian processes"))
        self.label_19.setText(_translate("MainWindow", "N_jobs"))
        self.label_39.setText(_translate("MainWindow", "Max_alpha"))
        self.label_40.setText(_translate("MainWindow", "Min_alpha"))
        self.label_41.setText(_translate("MainWindow", "Number"))
        self.label_43.setText(_translate("MainWindow", "Max_alpha"))
        self.label_44.setText(_translate("MainWindow", "Min_alpha"))
        self.label_42.setText(_translate("MainWindow", "Number_alpha"))
        self.label_45.setText(_translate("MainWindow", "Max_l1_ratio"))
        self.label_46.setText(_translate("MainWindow", "Min_l1_ratio"))
        self.label_47.setText(_translate("MainWindow", "Number_l1_ratio"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage3), _translate("MainWindow", "  Feature selection  "))
        self.groupBox_5.setTitle(_translate("MainWindow", "Methods"))
        self.radioButton_extractionunder.setText(_translate("MainWindow", "Extraction of majority-minority Tomek links"))
        self.radioButton_smotencover.setText(_translate("MainWindow", "SMOTENC - SMOTE for Nominal Continuous "))
        self.radioButton_nearmissunder.setText(_translate("MainWindow", "NearMiss-(1 and 2 and 3) "))
        self.label_12.setText(_translate("MainWindow", "Over-sampling the minority class"))
        self.radioButton_randunder.setText(_translate("MainWindow", "Random majority under-sampling with replacement"))
        self.radioButton_bsmoteover.setText(_translate("MainWindow", "bSMOTE(1 and 2) - Borderline SMOTE of types 1 and 2"))
        self.radioButton_randover.setText(_translate("MainWindow", "Random minority over-sampling with replacement"))
        self.label_13.setText(_translate("MainWindow", "Under-sampling the majority class(es)"))
        self.radioButton_smoteover.setText(_translate("MainWindow", "SMOTE - Synthetic Minority Over-sampling Technique"))
        self.radioButton_cludterunder.setText(_translate("MainWindow", "Under-sampling with Cluster Centroids"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Setting"))
        self.tabWidget_items.setTabText(self.tabWidget_items.indexOf(self.tabWidget_itemsPage4), _translate("MainWindow", "  Unbalance treatment  "))
        self.menuConfiguration_file_f.setTitle(_translate("MainWindow", "Configuration file (&F)"))
        self.menuHelp_G.setTitle(_translate("MainWindow", "Help (&H)"))
        self.menuSkin.setTitle(_translate("MainWindow", "Skin"))
        self.actionLoad_configuration.setText(_translate("MainWindow", "Load configuration"))
        self.actionSave_configuration.setText(_translate("MainWindow", "Save configuration"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionDarkOrange.setText(_translate("MainWindow", "DarkOrange"))
        self.actionGray.setText(_translate("MainWindow", "Gray"))
        self.actionBlue.setText(_translate("MainWindow", "Blue"))
        self.actionNavy.setText(_translate("MainWindow", "Navy"))
        self.actionClassic.setText(_translate("MainWindow", "Classic"))
        self.actionGet_all_available_configuraton.setText(_translate("MainWindow", "Get all available configuraton"))

